#MODEL SETTINGS
EMBEDDING_MODEL = "nomic-embed-text"
LLM_MODEL = "gemma3:1b"
OLLAMA_URL = "http://localhost:11434"

#CHUNKING SETTINGs
CHUNK_SIZE = 400
CHUNK_OVERLAP = 150

#RETRIEVAL SETTINGs
SIMILARITY_TOP_K = 4
RESPONSE_MODE = "compact"

#PATHS
DATA_DIR = "./data"
CHROMA_DB_PATH = "./chroma_db"
COLLECTION_NAME = "techcorp_docs"

CONFIDENCE_THRESHOLD = 0.5