import pandas as pd


training_questions = [
    # HR Questions (200)
    {"text": "how many vacation days do i get", "label": "HR"},
    {"text": "what is the pto policy", "label": "HR"},
    {"text": "can i take time off next week", "label": "HR"},
    {"text": "vacation days?", "label": "HR"},
    {"text": "wfh policy?", "label": "HR"},
    {"text": "how do i request sick leave", "label": "HR"},
    {"text": "parental leave duration", "label": "HR"},
    {"text": "maternity leave how many weeks", "label": "HR"},
    {"text": "does company offer paternity leave", "label": "HR"},
    {"text": "where submit pto request", "label": "HR"},
    {"text": "can i carry over unused vacation", "label": "HR"},
    {"text": "time off balance check", "label": "HR"},
    {"text": "sick leave carryover rules", "label": "HR"},
    {"text": "do i accrue pto during leave", "label": "HR"},
    {"text": "wanna work remote tomorrow", "label": "HR"},
    {"text": "remote work policy full time", "label": "HR"},
    {"text": "how many days can i work remotely", "label": "HR"},
    {"text": "hybrid schedule approval needed?", "label": "HR"},
    {"text": "flexible schedule options available", "label": "HR"},
    {"text": "compressed work week allowed?", "label": "HR"},
    {"text": "what if i need emergency time off", "label": "HR"},
    {"text": "benefits enrollment deadline", "label": "HR"},
    {"text": "health insurance options", "label": "HR"},
    {"text": "when does health insurance start", "label": "HR"},
    {"text": "medical insurance enrollment", "label": "HR"},
    {"text": "benefits eligibility period", "label": "HR"},
    {"text": "401k plan details", "label": "HR"},
    {"text": "company match 401k percentage", "label": "HR"},
    {"text": "how change retirement contributions", "label": "HR"},
    {"text": "retirement plan matching", "label": "HR"},
    {"text": "401k vesting schedule", "label": "HR"},
    {"text": "life insurance coverage amount", "label": "HR"},
    {"text": "is disability insurance included", "label": "HR"},
    {"text": "short term disability coverage", "label": "HR"},
    {"text": "long term disability benefits", "label": "HR"},
    {"text": "adding spouse to benefits", "label": "HR"},
    {"text": "can my partner get benefits", "label": "HR"},
    {"text": "dependent coverage options", "label": "HR"},
    {"text": "family health insurance cost", "label": "HR"},
    {"text": "dental insurance available?", "label": "HR"},
    {"text": "vision coverage included", "label": "HR"},
    {"text": "hsa vs ppo which better", "label": "HR"},
    {"text": "health savings account info", "label": "HR"},
    {"text": "fsa contribution limits", "label": "HR"},
    {"text": "dependent care fsa details", "label": "HR"},
    {"text": "open enrollment dates", "label": "HR"},
    {"text": "can i change benefits mid year", "label": "HR"},
    {"text": "beneficiary update process", "label": "HR"},
    {"text": "life insurance beneficiaries how to change", "label": "HR"},
    {"text": "employee handbook location", "label": "HR"},
    {"text": "where find hr policies", "label": "HR"},
    {"text": "company policies document", "label": "HR"},
    {"text": "dress code policy", "label": "HR"},
    {"text": "are jeans ok", "label": "HR"},
    {"text": "casual fridays?", "label": "HR"},
    {"text": "what should i wear to work", "label": "HR"},
    {"text": "code of conduct", "label": "HR"},
    {"text": "workplace conduct guidelines", "label": "HR"},
    {"text": "pto for new employees", "label": "HR"},
    {"text": "when can i start using vacation time", "label": "HR"},
    {"text": "new hire pto accrual", "label": "HR"},
    {"text": "paid time off accrual rate", "label": "HR"},
    {"text": "what happens to unused sick days", "label": "HR"},
    {"text": "how call in sick", "label": "HR"},
    {"text": "sick day notification process", "label": "HR"},
    {"text": "unpaid leave request", "label": "HR"},
    {"text": "can i take unpaid time off", "label": "HR"},
    {"text": "leave of absence policy", "label": "HR"},
    {"text": "bereavement leave how many days", "label": "HR"},
    {"text": "paid holidays list", "label": "HR"},
    {"text": "which holidays company observe", "label": "HR"},
    {"text": "floating holiday policy", "label": "HR"},
    {"text": "mental health days covered?", "label": "HR"},
    {"text": "can i take sabbatical", "label": "HR"},
    {"text": "sabbatical eligibility requirements", "label": "HR"},
    {"text": "adoption leave available", "label": "HR"},
    {"text": "fertility treatment leave", "label": "HR"},
    {"text": "military leave policy", "label": "HR"},
    {"text": "jury duty leave paid?", "label": "HR"},
    {"text": "voting time off", "label": "HR"},
    {"text": "volunteer time off available", "label": "HR"},
    {"text": "how many volunteer days", "label": "HR"},
    {"text": "work from home equipment stipend", "label": "HR"},
    {"text": "remote work reimbursement", "label": "HR"},
    {"text": "home office allowance", "label": "HR"},
    {"text": "internet reimbursement wfh", "label": "HR"},
    {"text": "can i work from another state", "label": "HR"},
    {"text": "working abroad temporary", "label": "HR"},
    {"text": "international remote work policy", "label": "HR"},
    {"text": "do i need approval work from home", "label": "HR"},
    {"text": "whats deal with flex time", "label": "HR"},
    {"text": "flextime scheduling", "label": "HR"},
    {"text": "core hours requirement", "label": "HR"},
    {"text": "part time benefits eligibility", "label": "HR"},
    {"text": "changing from full time to part time", "label": "HR"},
    {"text": "reduced schedule request", "label": "HR"},
    {"text": "job share opportunities", "label": "HR"},
    {"text": "workers comp claim how to file", "label": "HR"},
    {"text": "workplace injury reporting", "label": "HR"},
    {"text": "pto cash out option", "label": "HR"},
    {"text": "vacation payout at termination", "label": "HR"},
    {"text": "performance review schedule", "label": "HR"},
    {"text": "how often do we get reviews", "label": "HR"},
    {"text": "annual review process", "label": "HR"},
    {"text": "performance improvement plan", "label": "HR"},
    {"text": "pip process details", "label": "HR"},
    {"text": "promotion criteria", "label": "HR"},
    {"text": "how to report harassment", "label": "HR"},
    {"text": "workplace harassment policy", "label": "HR"},
    {"text": "discrimination complaint process", "label": "HR"},
    {"text": "whistleblower protection", "label": "HR"},
    {"text": "employee assistance program", "label": "HR"},
    {"text": "eap services available", "label": "HR"},
    {"text": "counseling benefits", "label": "HR"},
    {"text": "mental health resources", "label": "HR"},
    {"text": "tuition reimbursement how much", "label": "HR"},
    {"text": "education assistance program", "label": "HR"},
    {"text": "professional development budget", "label": "HR"},
    {"text": "training opportunities", "label": "HR"},
    {"text": "can company pay for certification", "label": "HR"},
    {"text": "probation period length", "label": "HR"},
    {"text": "new hire probationary period", "label": "HR"},
    {"text": "background check timeline", "label": "HR"},
    {"text": "drug testing policy", "label": "HR"},
    {"text": "employee referral bonus", "label": "HR"},
    {"text": "referral program details", "label": "HR"},
    {"text": "how much referral bonus", "label": "HR"},
    {"text": "work anniversary recognition", "label": "HR"},
    {"text": "service awards program", "label": "HR"},
    {"text": "lactation room availability", "label": "HR"},
    {"text": "nursing mothers accommodation", "label": "HR"},
    {"text": "religious accommodation request", "label": "HR"},
    {"text": "disability accommodation", "label": "HR"},
    {"text": "ada compliance process", "label": "HR"},
    {"text": "tattoo policy workplace", "label": "HR"},
    {"text": "piercing policy", "label": "HR"},
    {"text": "personal appearance standards", "label": "HR"},
    {"text": "remote work tax implications", "label": "HR"},
    {"text": "relocation assistance available", "label": "HR"},
    {"text": "moving expense reimbursement", "label": "HR"},
    {"text": "commuter benefits program", "label": "HR"},
    {"text": "transit subsidy amount", "label": "HR"},
    {"text": "parking reimbursement", "label": "HR"},
    {"text": "bike to work program", "label": "HR"},
    {"text": "wellness program benefits", "label": "HR"},
    {"text": "gym membership reimbursement", "label": "HR"},
    {"text": "fitness subsidy", "label": "HR"},
    {"text": "smoking cessation program", "label": "HR"},
    {"text": "vaccine requirements employment", "label": "HR"},
    {"text": "covid leave policy", "label": "HR"},
    {"text": "quarantine leave paid", "label": "HR"},
    {"text": "fmla eligibility", "label": "HR"},
    {"text": "family medical leave act", "label": "HR"},
    {"text": "intermittent fmla usage", "label": "HR"},
    {"text": "pregnancy accommodation", "label": "HR"},
    {"text": "miscarriage leave", "label": "HR"},
    {"text": "pet bereavement leave", "label": "HR"},
    {"text": "unlimited pto really unlimited?", "label": "HR"},
    {"text": "minimum vacation requirement", "label": "HR"},
    {"text": "mandatory time off", "label": "HR"},
    {"text": "blackout dates vacation", "label": "HR"},
    {"text": "vacation approval process", "label": "HR"},
    {"text": "how far advance request pto", "label": "HR"},
    {"text": "can manager deny vacation", "label": "HR"},
    {"text": "competing vacation requests", "label": "HR"},
    {"text": "summer hours policy", "label": "HR"},
    {"text": "early release fridays", "label": "HR"},
    {"text": "four day work week", "label": "HR"},
    {"text": "alternative work schedule", "label": "HR"},
    {"text": "shift differential pay", "label": "HR"},
    {"text": "on call compensation", "label": "HR"},
    {"text": "overtime policy exempt employees", "label": "HR"},
    {"text": "comp time instead of overtime", "label": "HR"},
    {"text": "personal day vs sick day", "label": "HR"},
    {"text": "vacaton day limits", "label": "HR"},
    {"text": "remote wrk guidelines", "label": "HR"},
    {"text": "insurence options", "label": "HR"},
    {"text": "benifits package", "label": "HR"},
    {"text": "retirment plan", "label": "HR"},
    {"text": "maternaty leave", "label": "HR"},
    {"text": "paturnity leave", "label": "HR"},
    {"text": "employy handbook", "label": "HR"},
    {"text": "sick leve policy", "label": "HR"},
    {"text": "time of request", "label": "HR"},
    
    # ENGINEERING Questions (200)
    {"text": "how submit pull request", "label": "ENGINEERING"},
    {"text": "code review process", "label": "ENGINEERING"},
    {"text": "who reviews my pr", "label": "ENGINEERING"},
    {"text": "pr requirements?", "label": "ENGINEERING"},
    {"text": "pull request template", "label": "ENGINEERING"},
    {"text": "how many approvals needed merge", "label": "ENGINEERING"},
    {"text": "git branching standards", "label": "ENGINEERING"},
    {"text": "how create new branch", "label": "ENGINEERING"},
    {"text": "branch naming convention", "label": "ENGINEERING"},
    {"text": "can i merge without code review", "label": "ENGINEERING"},
    {"text": "pr approval process", "label": "ENGINEERING"},
    {"text": "code review checklist", "label": "ENGINEERING"},
    {"text": "how long code review take", "label": "ENGINEERING"},
    {"text": "who can approve prs", "label": "ENGINEERING"},
    {"text": "self merge allowed?", "label": "ENGINEERING"},
    {"text": "deploy to production how", "label": "ENGINEERING"},
    {"text": "deployment process", "label": "ENGINEERING"},
    {"text": "when can i release code", "label": "ENGINEERING"},
    {"text": "production deployment schedule", "label": "ENGINEERING"},
    {"text": "ci/cd pipeline documentation", "label": "ENGINEERING"},
    {"text": "how does ci cd work here", "label": "ENGINEERING"},
    {"text": "pipeline configuration", "label": "ENGINEERING"},
    {"text": "trigger deployment", "label": "ENGINEERING"},
    {"text": "can i deploy directly to prod", "label": "ENGINEERING"},
    {"text": "release procedures", "label": "ENGINEERING"},
    {"text": "rollback deployment how", "label": "ENGINEERING"},
    {"text": "production rollback process", "label": "ENGINEERING"},
    {"text": "hotfix deployment", "label": "ENGINEERING"},
    {"text": "emergency release protocol", "label": "ENGINEERING"},
    {"text": "api documentation location", "label": "ENGINEERING"},
    {"text": "where api docs", "label": "ENGINEERING"},
    {"text": "rest api documentation", "label": "ENGINEERING"},
    {"text": "how document my code", "label": "ENGINEERING"},
    {"text": "documentation standards", "label": "ENGINEERING"},
    {"text": "code documentation requirements", "label": "ENGINEERING"},
    {"text": "need write unit tests?", "label": "ENGINEERING"},
    {"text": "testing policy", "label": "ENGINEERING"},
    {"text": "unit test requirements", "label": "ENGINEERING"},
    {"text": "run integration tests", "label": "ENGINEERING"},
    {"text": "test coverage required", "label": "ENGINEERING"},
    {"text": "minimum code coverage", "label": "ENGINEERING"},
    {"text": "where write tests", "label": "ENGINEERING"},
    {"text": "testing framework used", "label": "ENGINEERING"},
    {"text": "e2e testing setup", "label": "ENGINEERING"},
    {"text": "tech stack company uses", "label": "ENGINEERING"},
    {"text": "what programming languages allowed", "label": "ENGINEERING"},
    {"text": "technology stack", "label": "ENGINEERING"},
    {"text": "system architecture overview", "label": "ENGINEERING"},
    {"text": "architecture docs location", "label": "ENGINEERING"},
    {"text": "coding standards", "label": "ENGINEERING"},
    {"text": "best practices codebase", "label": "ENGINEERING"},
    {"text": "style guide", "label": "ENGINEERING"},
    {"text": "linting rules", "label": "ENGINEERING"},
    {"text": "code formatter we use", "label": "ENGINEERING"},
    {"text": "git workflow", "label": "ENGINEERING"},
    {"text": "rebase vs merge", "label": "ENGINEERING"},
    {"text": "how rebase branch", "label": "ENGINEERING"},
    {"text": "squash commits before merge", "label": "ENGINEERING"},
    {"text": "commit message format", "label": "ENGINEERING"},
    {"text": "what build fails", "label": "ENGINEERING"},
    {"text": "ci pipeline failing", "label": "ENGINEERING"},
    {"text": "build error resolution", "label": "ENGINEERING"},
    {"text": "pipeline duration", "label": "ENGINEERING"},
    {"text": "can skip tests in pr", "label": "ENGINEERING"},
    {"text": "bypass ci checks", "label": "ENGINEERING"},
    {"text": "environments available", "label": "ENGINEERING"},
    {"text": "access staging environment", "label": "ENGINEERING"},
    {"text": "dev environment setup", "label": "ENGINEERING"},
    {"text": "local development guide", "label": "ENGINEERING"},
    {"text": "api rate limits", "label": "ENGINEERING"},
    {"text": "endpoint rate limiting", "label": "ENGINEERING"},
    {"text": "how add new endpoint", "label": "ENGINEERING"},
    {"text": "api versioning strategy", "label": "ENGINEERING"},
    {"text": "backend framework", "label": "ENGINEERING"},
    {"text": "frontend framework", "label": "ENGINEERING"},
    {"text": "database we use", "label": "ENGINEERING"},
    {"text": "version control system", "label": "ENGINEERING"},
    {"text": "how often commit code", "label": "ENGINEERING"},
    {"text": "commit frequency best practice", "label": "ENGINEERING"},
    {"text": "merge conflicts resolution", "label": "ENGINEERING"},
    {"text": "resolve merge conflict", "label": "ENGINEERING"},
    {"text": "code ownership model", "label": "ENGINEERING"},
    {"text": "codeowners file", "label": "ENGINEERING"},
    {"text": "pair programming encouraged?", "label": "ENGINEERING"},
    {"text": "mob programming sessions", "label": "ENGINEERING"},
    {"text": "technical debt tracking", "label": "ENGINEERING"},
    {"text": "refactoring guidelines", "label": "ENGINEERING"},
    {"text": "which ide should use", "label": "ENGINEERING"},
    {"text": "recommended code editor", "label": "ENGINEERING"},
    {"text": "editor plugins required", "label": "ENGINEERING"},
    {"text": "microservices architecture", "label": "ENGINEERING"},
    {"text": "monolith vs microservices", "label": "ENGINEERING"},
    {"text": "service communication pattern", "label": "ENGINEERING"},
    {"text": "backward compatibility requirements", "label": "ENGINEERING"},
    {"text": "breaking changes protocol", "label": "ENGINEERING"},
    {"text": "api deprecation process", "label": "ENGINEERING"},
    {"text": "code freeze dates", "label": "ENGINEERING"},
    {"text": "release freeze period", "label": "ENGINEERING"},
    {"text": "postmortem process incidents", "label": "ENGINEERING"},
    {"text": "incident report template", "label": "ENGINEERING"},
    {"text": "can use beta libraries", "label": "ENGINEERING"},
    {"text": "third party dependency approval", "label": "ENGINEERING"},
    {"text": "dependency update policy", "label": "ENGINEERING"},
    {"text": "security patch process", "label": "ENGINEERING"},
    {"text": "open source contribution allowed?", "label": "ENGINEERING"},
    {"text": "contributing to oss", "label": "ENGINEERING"},
    {"text": "design review meeting", "label": "ENGINEERING"},
    {"text": "architecture review process", "label": "ENGINEERING"},
    {"text": "technical rfc process", "label": "ENGINEERING"},
    {"text": "design doc template", "label": "ENGINEERING"},
    {"text": "load testing requirements", "label": "ENGINEERING"},
    {"text": "performance testing before launch", "label": "ENGINEERING"},
    {"text": "stress testing guidelines", "label": "ENGINEERING"},
    {"text": "accessibility standards", "label": "ENGINEERING"},
    {"text": "wcag compliance level", "label": "ENGINEERING"},
    {"text": "mobile app deployment", "label": "ENGINEERING"},
    {"text": "app store release process", "label": "ENGINEERING"},
    {"text": "feature branch lifetime", "label": "ENGINEERING"},
    {"text": "stale branch policy", "label": "ENGINEERING"},
    {"text": "squash vs merge commits", "label": "ENGINEERING"},
    {"text": "rebase policy", "label": "ENGINEERING"},
    {"text": "error tracking tool", "label": "ENGINEERING"},
    {"text": "logging framework", "label": "ENGINEERING"},
    {"text": "monitoring setup", "label": "ENGINEERING"},
    {"text": "apm configuration", "label": "ENGINEERING"},
    {"text": "disaster recovery runbook", "label": "ENGINEERING"},
    {"text": "backup procedures", "label": "ENGINEERING"},
    {"text": "on call rotation", "label": "ENGINEERING"},
    {"text": "pager duty schedule", "label": "ENGINEERING"},
    {"text": "incident severity levels", "label": "ENGINEERING"},
    {"text": "sla requirements", "label": "ENGINEERING"},
    {"text": "database migration process", "label": "ENGINEERING"},
    {"text": "schema changes approval", "label": "ENGINEERING"},
    {"text": "feature flags usage", "label": "ENGINEERING"},
    {"text": "feature toggle documentation", "label": "ENGINEERING"},
    {"text": "canary deployment", "label": "ENGINEERING"},
    {"text": "blue green deployment", "label": "ENGINEERING"},
    {"text": "production access request", "label": "ENGINEERING"},
    {"text": "need access prod logs", "label": "ENGINEERING"},
    {"text": "vpn for prod access", "label": "ENGINEERING"},
    {"text": "graphql vs rest", "label": "ENGINEERING"},
    {"text": "api design guidelines", "label": "ENGINEERING"},
    {"text": "security review before release?", "label": "ENGINEERING"},
    {"text": "penetration testing schedule", "label": "ENGINEERING"},
    {"text": "vulnerability scanning", "label": "ENGINEERING"},
    {"text": "secrets management", "label": "ENGINEERING"},
    {"text": "environment variables config", "label": "ENGINEERING"},
    {"text": "docker setup", "label": "ENGINEERING"},
    {"text": "kubernetes deployment", "label": "ENGINEERING"},
    {"text": "container orchestration", "label": "ENGINEERING"},
    {"text": "infrastructure as code", "label": "ENGINEERING"},
    {"text": "terraform usage", "label": "ENGINEERING"},
    {"text": "cloud provider we use", "label": "ENGINEERING"},
    {"text": "aws vs azure", "label": "ENGINEERING"},
    {"text": "serverless architecture", "label": "ENGINEERING"},
    {"text": "lambda functions deployment", "label": "ENGINEERING"},
    {"text": "queue system we use", "label": "ENGINEERING"},
    {"text": "message broker configuration", "label": "ENGINEERING"},
    {"text": "caching strategy", "label": "ENGINEERING"},
    {"text": "redis usage guidelines", "label": "ENGINEERING"},
    {"text": "cdn configuration", "label": "ENGINEERING"},
    {"text": "static assets deployment", "label": "ENGINEERING"},
    {"text": "build optimization", "label": "ENGINEERING"},
    {"text": "bundle size limits", "label": "ENGINEERING"},
    {"text": "webpack configuration", "label": "ENGINEERING"},
    {"text": "npm vs yarn", "label": "ENGINEERING"},
    {"text": "package manager preference", "label": "ENGINEERING"},
    {"text": "node version required", "label": "ENGINEERING"},
    {"text": "python version standard", "label": "ENGINEERING"},
    {"text": "java version policy", "label": "ENGINEERING"},
    {"text": "trunk based development", "label": "ENGINEERING"},
    {"text": "git flow vs trunk", "label": "ENGINEERING"},
    {"text": "can push to main", "label": "ENGINEERING"},
    {"text": "protected branches", "label": "ENGINEERING"},
    {"text": "branch protection rules", "label": "ENGINEERING"},
    {"text": "code review turnaround time", "label": "ENGINEERING"},
    {"text": "pr size limit", "label": "ENGINEERING"},
    {"text": "pul request", "label": "ENGINEERING"},
    {"text": "deploi to prod", "label": "ENGINEERING"},
    {"text": "ci cd setup", "label": "ENGINEERING"},
    {"text": "merge conflics", "label": "ENGINEERING"},
    {"text": "apii documentation", "label": "ENGINEERING"},
    {"text": "unit test coverage", "label": "ENGINEERING"},
    {"text": "intergration tests", "label": "ENGINEERING"},
    {"text": "git workflo", "label": "ENGINEERING"},
    {"text": "code reveiw", "label": "ENGINEERING"},
    
    # FINANCE Questions (200)
    {"text": "submit expense report", "label": "FINANCE"},
    {"text": "where upload receipts", "label": "FINANCE"},
    {"text": "get reimbursed expenses", "label": "FINANCE"},
    {"text": "expense limit?", "label": "FINANCE"},
    {"text": "reimbursement timeline", "label": "FINANCE"},
    {"text": "what expenses can submit", "label": "FINANCE"},
    {"text": "reimbursement how long", "label": "FINANCE"},
    {"text": "need receipts all expenses", "label": "FINANCE"},
    {"text": "expense policy", "label": "FINANCE"},
    {"text": "can expense meals", "label": "FINANCE"},
    {"text": "meal reimbursement limit", "label": "FINANCE"},
    {"text": "submit travel expenses", "label": "FINANCE"},
    {"text": "travel expense report", "label": "FINANCE"},
    {"text": "per diem rate", "label": "FINANCE"},
    {"text": "how much per diem", "label": "FINANCE"},
    {"text": "daily allowance travel", "label": "FINANCE"},
    {"text": "expense mileage", "label": "FINANCE"},
    {"text": "mileage reimbursement rate", "label": "FINANCE"},
    {"text": "personal car business use", "label": "FINANCE"},
    {"text": "book hotel business travel", "label": "FINANCE"},
    {"text": "hotel expense limit", "label": "FINANCE"},
    {"text": "accommodation booking", "label": "FINANCE"},
    {"text": "can book own flights", "label": "FINANCE"},
    {"text": "expense airfare", "label": "FINANCE"},
    {"text": "flight booking policy", "label": "FINANCE"},
    {"text": "meal expenses covered", "label": "FINANCE"},
    {"text": "expense client dinners", "label": "FINANCE"},
    {"text": "business meal guidelines", "label": "FINANCE"},
    {"text": "department budget", "label": "FINANCE"},
    {"text": "request budget approval", "label": "FINANCE"},
    {"text": "budget allocation", "label": "FINANCE"},
    {"text": "approval before purchasing", "label": "FINANCE"},
    {"text": "purchase approval threshold", "label": "FINANCE"},
    {"text": "create purchase order", "label": "FINANCE"},
    {"text": "po process", "label": "FINANCE"},
    {"text": "purchase order system", "label": "FINANCE"},
    {"text": "submit invoice", "label": "FINANCE"},
    {"text": "invoice submission process", "label": "FINANCE"},
    {"text": "vendor invoice payment", "label": "FINANCE"},
    {"text": "add new vendor", "label": "FINANCE"},
    {"text": "vendor onboarding", "label": "FINANCE"},
    {"text": "vendor approval process", "label": "FINANCE"},
    {"text": "get corporate credit card", "label": "FINANCE"},
    {"text": "corporate card application", "label": "FINANCE"},
    {"text": "company credit card policy", "label": "FINANCE"},
    {"text": "what use corporate card for", "label": "FINANCE"},
    {"text": "credit card limits", "label": "FINANCE"},
    {"text": "corp card spending limit", "label": "FINANCE"},
    {"text": "reconcile corporate card", "label": "FINANCE"},
    {"text": "credit card statement due", "label": "FINANCE"},
    {"text": "expense reconciliation", "label": "FINANCE"},
    {"text": "request payment vendor", "label": "FINANCE"},
    {"text": "vendor payment process", "label": "FINANCE"},
    {"text": "cash advance travel", "label": "FINANCE"},
    {"text": "request cash advance", "label": "FINANCE"},
    {"text": "travel advance request", "label": "FINANCE"},
    {"text": "documentation needed expenses", "label": "FINANCE"},
    {"text": "expense report form", "label": "FINANCE"},
    {"text": "categorize expenses", "label": "FINANCE"},
    {"text": "expense categories", "label": "FINANCE"},
    {"text": "lost receipt what now", "label": "FINANCE"},
    {"text": "missing receipt policy", "label": "FINANCE"},
    {"text": "expense uber rides", "label": "FINANCE"},
    {"text": "rideshare reimbursement", "label": "FINANCE"},
    {"text": "transportation costs reimbursable", "label": "FINANCE"},
    {"text": "expense parking", "label": "FINANCE"},
    {"text": "parking reimbursement", "label": "FINANCE"},
    {"text": "approval large purchases", "label": "FINANCE"},
    {"text": "who approves expense reports", "label": "FINANCE"},
    {"text": "expense approval workflow", "label": "FINANCE"},
    {"text": "spend without approval limit", "label": "FINANCE"},
    {"text": "over budget what happens", "label": "FINANCE"},
    {"text": "budget overrun protocol", "label": "FINANCE"},
    {"text": "expense conference fees", "label": "FINANCE"},
    {"text": "conference registration reimbursement", "label": "FINANCE"},
    {"text": "pay invoice", "label": "FINANCE"},
    {"text": "payment methods accepted", "label": "FINANCE"},
    {"text": "vendor payment timeline", "label": "FINANCE"},
    {"text": "direct deposit setup", "label": "FINANCE"},
    {"text": "payroll direct deposit", "label": "FINANCE"},
    {"text": "pay stub access", "label": "FINANCE"},
    {"text": "view paystubs online", "label": "FINANCE"},
    {"text": "overtime pay calculation", "label": "FINANCE"},
    {"text": "ot compensation", "label": "FINANCE"},
    {"text": "bonus payout schedule", "label": "FINANCE"},
    {"text": "when bonuses paid", "label": "FINANCE"},
    {"text": "commission structure", "label": "FINANCE"},
    {"text": "commission payment terms", "label": "FINANCE"},
    {"text": "relocation expenses covered?", "label": "FINANCE"},
    {"text": "moving expense policy", "label": "FINANCE"},
    {"text": "sign on bonus repayment", "label": "FINANCE"},
    {"text": "signing bonus terms", "label": "FINANCE"},
    {"text": "professional development budget", "label": "FINANCE"},
    {"text": "training budget annual", "label": "FINANCE"},
    {"text": "certification reimbursement", "label": "FINANCE"},
    {"text": "exam fee reimbursement", "label": "FINANCE"},
    {"text": "gym membership subsidy", "label": "FINANCE"},
    {"text": "fitness reimbursement", "label": "FINANCE"},
    {"text": "coworking space expense", "label": "FINANCE"},
    {"text": "home office furniture budget", "label": "FINANCE"},
    {"text": "office equipment reimbursement", "label": "FINANCE"},
    {"text": "client entertainment guidelines", "label": "FINANCE"},
    {"text": "entertainment expense policy", "label": "FINANCE"},
    {"text": "team lunch expense", "label": "FINANCE"},
    {"text": "team building expense", "label": "FINANCE"},
    {"text": "gift card expense ok?", "label": "FINANCE"},
    {"text": "gift policy vendors", "label": "FINANCE"},
    {"text": "subscription services approval", "label": "FINANCE"},
    {"text": "software subscription expense", "label": "FINANCE"},
    {"text": "saas purchase approval", "label": "FINANCE"},
    {"text": "expense currency conversion", "label": "FINANCE"},
    {"text": "foreign currency expenses", "label": "FINANCE"},
    {"text": "international expense rates", "label": "FINANCE"},
    {"text": "vat reclaim expenses", "label": "FINANCE"},
    {"text": "tax refund international", "label": "FINANCE"},
    {"text": "consultant payment terms", "label": "FINANCE"},
    {"text": "contractor invoice process", "label": "FINANCE"},
    {"text": "freelancer payment", "label": "FINANCE"},
    {"text": "capital expenditure threshold", "label": "FINANCE"},
    {"text": "capex vs opex", "label": "FINANCE"},
    {"text": "asset capitalization policy", "label": "FINANCE"},
    {"text": "year end close deadlines", "label": "FINANCE"},
    {"text": "fiscal year end", "label": "FINANCE"},
    {"text": "audit preparation", "label": "FINANCE"},
    {"text": "financial audit schedule", "label": "FINANCE"},
    {"text": "financial reporting calendar", "label": "FINANCE"},
    {"text": "monthly close schedule", "label": "FINANCE"},
    {"text": "cost center allocation", "label": "FINANCE"},
    {"text": "charge code usage", "label": "FINANCE"},
    {"text": "project code expenses", "label": "FINANCE"},
    {"text": "travel booking system", "label": "FINANCE"},
    {"text": "corporate travel portal", "label": "FINANCE"},
    {"text": "preferred vendors travel", "label": "FINANCE"},
    {"text": "petty cash available?", "label": "FINANCE"},
    {"text": "petty cash request", "label": "FINANCE"},
    {"text": "international travel expenses", "label": "FINANCE"},
    {"text": "overseas travel policy", "label": "FINANCE"},
    {"text": "alcohol clients expense", "label": "FINANCE"},
    {"text": "alcohol expense policy", "label": "FINANCE"},
    {"text": "expense tips gratuity", "label": "FINANCE"},
    {"text": "tipping guidelines expenses", "label": "FINANCE"},
    {"text": "split expenses projects", "label": "FINANCE"},
    {"text": "allocate expense multiple departments", "label": "FINANCE"},
    {"text": "taxi vs uber policy", "label": "FINANCE"},
    {"text": "ground transportation preference", "label": "FINANCE"},
    {"text": "rental car policy", "label": "FINANCE"},
    {"text": "car rental expense", "label": "FINANCE"},
    {"text": "equipment purchase request", "label": "FINANCE"},
    {"text": "hardware purchase approval", "label": "FINANCE"},
    {"text": "company amex benefits", "label": "FINANCE"},
    {"text": "credit card rewards policy", "label": "FINANCE"},
    {"text": "international per diem", "label": "FINANCE"},
    {"text": "overseas daily allowance", "label": "FINANCE"},
    {"text": "expense report rejected why", "label": "FINANCE"},
    {"text": "expense denial reason", "label": "FINANCE"},
    {"text": "resubmit expense report", "label": "FINANCE"},
    {"text": "mobile phone reimbursement", "label": "FINANCE"},
    {"text": "cell phone stipend", "label": "FINANCE"},
    {"text": "internet home expense", "label": "FINANCE"},
    {"text": "home internet reimbursement", "label": "FINANCE"},
    {"text": "client gift limits", "label": "FINANCE"},
    {"text": "gift expense threshold", "label": "FINANCE"},
    {"text": "conference who pays", "label": "FINANCE"},
    {"text": "event registration expense", "label": "FINANCE"},
    {"text": "mileage tracker app", "label": "FINANCE"},
    {"text": "mileage log requirements", "label": "FINANCE"},
    {"text": "quarterly budget review", "label": "FINANCE"},
    {"text": "budget variance analysis", "label": "FINANCE"},
    {"text": "forecast vs actual", "label": "FINANCE"},
    {"text": "wire transfer request", "label": "FINANCE"},
    {"text": "ach payment setup", "label": "FINANCE"},
    {"text": "check request process", "label": "FINANCE"},
    {"text": "paper check issuance", "label": "FINANCE"},
    {"text": "1099 contractor form", "label": "FINANCE"},
    {"text": "w9 vendor form", "label": "FINANCE"},
    {"text": "tax documentation vendors", "label": "FINANCE"},
    {"text": "expence report", "label": "FINANCE"},
    {"text": "reciept upload", "label": "FINANCE"},
    {"text": "reimburse expenses", "label": "FINANCE"},
    {"text": "travle expenses", "label": "FINANCE"},
    {"text": "perdiem rate", "label": "FINANCE"},
    {"text": "milage reimbursment", "label": "FINANCE"},
    {"text": "coporate card", "label": "FINANCE"},
    {"text": "purchas order", "label": "FINANCE"},
    {"text": "invioce submit", "label": "FINANCE"},
    {"text": "vender payment", "label": "FINANCE"},
    
    # GENERAL Questions (200)
    {"text": "first day what do", "label": "GENERAL"},
    {"text": "onboarding location", "label": "GENERAL"},
    {"text": "new hire orientation", "label": "GENERAL"},
    {"text": "orientation schedule", "label": "GENERAL"},
    {"text": "first day bring what", "label": "GENERAL"},
    {"text": "employee badge", "label": "GENERAL"},
    {"text": "get id badge", "label": "GENERAL"},
    {"text": "where park", "label": "GENERAL"},
    {"text": "parking location", "label": "GENERAL"},
    {"text": "free parking office", "label": "GENERAL"},
    {"text": "parking pass", "label": "GENERAL"},
    {"text": "office access", "label": "GENERAL"},
    {"text": "building entry", "label": "GENERAL"},
    {"text": "office hours", "label": "GENERAL"},
    {"text": "work hours", "label": "GENERAL"},
    {"text": "get laptop", "label": "GENERAL"},
    {"text": "equipment pickup", "label": "GENERAL"},
    {"text": "contact for it equipment", "label": "GENERAL"},
    {"text": "request new equipment", "label": "GENERAL"},
    {"text": "it help desk", "label": "GENERAL"},
    {"text": "tech support contact", "label": "GENERAL"},
    {"text": "reset password", "label": "GENERAL"},
    {"text": "password reset", "label": "GENERAL"},
    {"text": "forgot password", "label": "GENERAL"},
    {"text": "company mission", "label": "GENERAL"},
    {"text": "mission statement", "label": "GENERAL"},
    {"text": "company values", "label": "GENERAL"},
    {"text": "core values", "label": "GENERAL"},
    {"text": "company culture", "label": "GENERAL"},
    {"text": "culture values", "label": "GENERAL"},
    {"text": "what company do", "label": "GENERAL"},
    {"text": "company products", "label": "GENERAL"},
    {"text": "who ceo", "label": "GENERAL"},
    {"text": "leadership team", "label": "GENERAL"},
    {"text": "executive team", "label": "GENERAL"},
    {"text": "org chart", "label": "GENERAL"},
    {"text": "organizational structure", "label": "GENERAL"},
    {"text": "find contact info", "label": "GENERAL"},
    {"text": "employee directory", "label": "GENERAL"},
    {"text": "staff directory", "label": "GENERAL"},
    {"text": "who my manager", "label": "GENERAL"},
    {"text": "supervisor name", "label": "GENERAL"},
    {"text": "who report to", "label": "GENERAL"},
    {"text": "reporting structure", "label": "GENERAL"},
    {"text": "contact about payroll", "label": "GENERAL"},
    {"text": "payroll department", "label": "GENERAL"},
    {"text": "facilities issues", "label": "GENERAL"},
    {"text": "building maintenance", "label": "GENERAL"},
    {"text": "join team", "label": "GENERAL"},
    {"text": "team structure", "label": "GENERAL"},
    {"text": "teams at company", "label": "GENERAL"},
    {"text": "departments list", "label": "GENERAL"},
    {"text": "main office location", "label": "GENERAL"},
    {"text": "office address", "label": "GENERAL"},
    {"text": "multiple offices", "label": "GENERAL"},
    {"text": "office locations", "label": "GENERAL"},
    {"text": "what floor hr", "label": "GENERAL"},
    {"text": "hr department location", "label": "GENERAL"},
    {"text": "cafeteria location", "label": "GENERAL"},
    {"text": "lunch room", "label": "GENERAL"},
    {"text": "free coffee", "label": "GENERAL"},
    {"text": "kitchen amenities", "label": "GENERAL"},
    {"text": "office amenities", "label": "GENERAL"},
    {"text": "building facilities", "label": "GENERAL"},
    {"text": "book conference room", "label": "GENERAL"},
    {"text": "meeting room reservation", "label": "GENERAL"},
    {"text": "reserve meeting space", "label": "GENERAL"},
    {"text": "meeting rooms find", "label": "GENERAL"},
    {"text": "conference room booking system", "label": "GENERAL"},
    {"text": "badge doesn't work", "label": "GENERAL"},
    {"text": "access card issue", "label": "GENERAL"},
    {"text": "building access after hours", "label": "GENERAL"},
    {"text": "weekend office access", "label": "GENERAL"},
    {"text": "gym office", "label": "GENERAL"},
    {"text": "fitness center", "label": "GENERAL"},
    {"text": "wifi password", "label": "GENERAL"},
    {"text": "wireless network", "label": "GENERAL"},
    {"text": "connect network", "label": "GENERAL"},
    {"text": "network access", "label": "GENERAL"},
    {"text": "ask about it problems", "label": "GENERAL"},
    {"text": "technical support", "label": "GENERAL"},
    {"text": "software needed installed", "label": "GENERAL"},
    {"text": "required software", "label": "GENERAL"},
    {"text": "access company email", "label": "GENERAL"},
    {"text": "email setup", "label": "GENERAL"},
    {"text": "onboarding checklist", "label": "GENERAL"},
    {"text": "new hire checklist", "label": "GENERAL"},
    {"text": "when get paid", "label": "GENERAL"},
    {"text": "pay schedule", "label": "GENERAL"},
    {"text": "payday", "label": "GENERAL"},
    {"text": "who founded company", "label": "GENERAL"},
    {"text": "company founder", "label": "GENERAL"},
    {"text": "company history", "label": "GENERAL"},
    {"text": "company background", "label": "GENERAL"},
    {"text": "how many employees", "label": "GENERAL"},
    {"text": "company size", "label": "GENERAL"},
    {"text": "headcount", "label": "GENERAL"},
    {"text": "nda signing", "label": "GENERAL"},
    {"text": "confidentiality agreement", "label": "GENERAL"},
    {"text": "company newsletter", "label": "GENERAL"},
    {"text": "internal communications", "label": "GENERAL"},
    {"text": "internal job postings", "label": "GENERAL"},
    {"text": "open positions", "label": "GENERAL"},
    {"text": "career opportunities", "label": "GENERAL"},
    {"text": "mentorship program", "label": "GENERAL"},
    {"text": "mentor matching", "label": "GENERAL"},
    {"text": "lunch learn schedule", "label": "GENERAL"},
    {"text": "learning sessions", "label": "GENERAL"},
    {"text": "town hall frequency", "label": "GENERAL"},
    {"text": "all hands meeting", "label": "GENERAL"},
    {"text": "anonymous feedback", "label": "GENERAL"},
    {"text": "suggestion box", "label": "GENERAL"},
    {"text": "office closure days", "label": "GENERAL"},
    {"text": "company holidays", "label": "GENERAL"},
    {"text": "smoking area", "label": "GENERAL"},
    {"text": "designated smoking", "label": "GENERAL"},
    {"text": "bike storage", "label": "GENERAL"},
    {"text": "bicycle parking", "label": "GENERAL"},
    {"text": "shower facilities", "label": "GENERAL"},
    {"text": "locker room", "label": "GENERAL"},
    {"text": "kitchen supplies", "label": "GENERAL"},
    {"text": "break room supplies", "label": "GENERAL"},
    {"text": "recycling bins", "label": "GENERAL"},
    {"text": "waste disposal", "label": "GENERAL"},
    {"text": "noise level policy", "label": "GENERAL"},
    {"text": "quiet areas", "label": "GENERAL"},
    {"text": "phone booth reservation", "label": "GENERAL"},
    {"text": "privacy pod booking", "label": "GENERAL"},
    {"text": "standing desk request", "label": "GENERAL"},
    {"text": "ergonomic equipment", "label": "GENERAL"},
    {"text": "dual monitor setup", "label": "GENERAL"},
    {"text": "monitor request", "label": "GENERAL"},
    {"text": "headphones provided", "label": "GENERAL"},
    {"text": "audio equipment", "label": "GENERAL"},
    {"text": "office supplies ordering", "label": "GENERAL"},
    {"text": "stationery request", "label": "GENERAL"},
    {"text": "business cards request", "label": "GENERAL"},
    {"text": "business card order", "label": "GENERAL"},
    {"text": "name plate desk", "label": "GENERAL"},
    {"text": "desk nameplate", "label": "GENERAL"},
    {"text": "company logo usage", "label": "GENERAL"},
    {"text": "brand guidelines", "label": "GENERAL"},
    {"text": "social media policy", "label": "GENERAL"},
    {"text": "social media guidelines", "label": "GENERAL"},
    {"text": "patent assignment", "label": "GENERAL"},
    {"text": "ip agreement", "label": "GENERAL"},
    {"text": "exit interview", "label": "GENERAL"},
    {"text": "offboarding process", "label": "GENERAL"},
    {"text": "laptop setup", "label": "GENERAL"},
    {"text": "computer configuration", "label": "GENERAL"},
    {"text": "cant login", "label": "GENERAL"},
    {"text": "login issues", "label": "GENERAL"},
    {"text": "meeting room booking", "label": "GENERAL"},
    {"text": "room schedule", "label": "GENERAL"},
    {"text": "company swag", "label": "GENERAL"},
    {"text": "branded merchandise", "label": "GENERAL"},
    {"text": "all hands when", "label": "GENERAL"},
    {"text": "company meeting schedule", "label": "GENERAL"},
    {"text": "slack channels", "label": "GENERAL"},
    {"text": "communication channels", "label": "GENERAL"},
    {"text": "org structure", "label": "GENERAL"},
    {"text": "hierarchy chart", "label": "GENERAL"},
    {"text": "vpn setup", "label": "GENERAL"},
    {"text": "remote access", "label": "GENERAL"},
    {"text": "printer floor", "label": "GENERAL"},
    {"text": "copy machine location", "label": "GENERAL"},
    {"text": "building security", "label": "GENERAL"},
    {"text": "security desk", "label": "GENERAL"},
    {"text": "emergency contacts", "label": "GENERAL"},
    {"text": "emergency procedures", "label": "GENERAL"},
    {"text": "company timeline", "label": "GENERAL"},
    {"text": "company milestones", "label": "GENERAL"},
    {"text": "values statement", "label": "GENERAL"},
    {"text": "diversity initiatives", "label": "GENERAL"},
    {"text": "dei programs", "label": "GENERAL"},
    {"text": "employee resource groups", "label": "GENERAL"},
    {"text": "erg list", "label": "GENERAL"},
    {"text": "mail room", "label": "GENERAL"},
    {"text": "package delivery", "label": "GENERAL"},
    {"text": "visitor policy", "label": "GENERAL"},
    {"text": "guest check in", "label": "GENERAL"},
    {"text": "company events", "label": "GENERAL"},
    {"text": "social calendar", "label": "GENERAL"},
    {"text": "feedback system", "label": "GENERAL"},
    {"text": "employee survey", "label": "GENERAL"},
    {"text": "employee discounts", "label": "GENERAL"},
    {"text": "perks program", "label": "GENERAL"},
    {"text": "wellness program", "label": "GENERAL"},
    {"text": "health initiatives", "label": "GENERAL"},
    {"text": "transfer departments", "label": "GENERAL"},
    {"text": "internal mobility", "label": "GENERAL"},
    {"text": "first day time", "label": "GENERAL"},
    {"text": "onboaring process", "label": "GENERAL"},
    {"text": "employe badge", "label": "GENERAL"},
    {"text": "ofice hours", "label": "GENERAL"},
    {"text": "compny mission", "label": "GENERAL"},
    {"text": "organiztion chart", "label": "GENERAL"},
    {"text": "employe directory", "label": "GENERAL"},
    {"text": "wifi pasword", "label": "GENERAL"},
    {"text": "acces email", "label": "GENERAL"},
    {"text": "paking location", "label": "GENERAL"}
]

df = pd.DataFrame(training_questions)
df.to_csv("./data/processed/question_training_data.csv", index=False)