import pandas as pd


training_questions = [
    # HR QUESTIONS (~300)
    {"text": "how many vacation days do i get", "label": "HR"},
    {"text": "what is the pto policy", "label": "HR"},
    {"text": "how do i request time off", "label": "HR"},
    {"text": "can i carry over unused vacation days", "label": "HR"},
    {"text": "how much pto do i accrue per pay period", "label": "HR"},
    {"text": "what are the company holidays", "label": "HR"},
    {"text": "do we get the day after thanksgiving off", "label": "HR"},
    {"text": "how do i call in sick", "label": "HR"},
    {"text": "what is the sick leave policy", "label": "HR"},
    {"text": "how many sick days can i take", "label": "HR"},
    {"text": "can i use pto for sick days", "label": "HR"},
    {"text": "what is the parental leave policy", "label": "HR"},
    {"text": "how much maternity leave do i get", "label": "HR"},
    {"text": "do fathers get paternity leave", "label": "HR"},
    {"text": "how long is paid parental leave", "label": "HR"},
    {"text": "when does parental leave start", "label": "HR"},
    {"text": "can i take parental leave for adoption", "label": "HR"},
    {"text": "what benefits do foster parents get", "label": "HR"},
    {"text": "how do i apply for parental leave", "label": "HR"},
    {"text": "do i need to notify anyone before taking parental leave", "label": "HR"},
    {"text": "what health insurance plans are available", "label": "HR"},
    {"text": "whats the difference between ppo and hmo", "label": "HR"},
    {"text": "how much does health insurance cost", "label": "HR"},
    {"text": "when can i enroll in benefits", "label": "HR"},
    {"text": "what is the benefits enrollment deadline", "label": "HR"},
    {"text": "can i add my spouse to health insurance", "label": "HR"},
    {"text": "how do i add dependents to my insurance", "label": "HR"},
    {"text": "does the company offer dental insurance", "label": "HR"},
    {"text": "is vision coverage included", "label": "HR"},
    {"text": "what does the dental plan cover", "label": "HR"},
    {"text": "how much is the deductible for the ppo plan", "label": "HR"},
    {"text": "what is the out of pocket maximum", "label": "HR"},
    {"text": "do i need a referral to see a specialist", "label": "HR"},
    {"text": "can i use out of network providers", "label": "HR"},
    {"text": "what is covered under preventive care", "label": "HR"},
    {"text": "are mental health services covered", "label": "HR"},
    {"text": "how much is a primary care visit copay", "label": "HR"},
    {"text": "what is the emergency room copay", "label": "HR"},
    {"text": "does insurance cover prescriptions", "label": "HR"},
    {"text": "how much do generic drugs cost", "label": "HR"},
    {"text": "what is the 401k match", "label": "HR"},
    {"text": "how much does the company match for retirement", "label": "HR"},
    {"text": "when can i enroll in the 401k", "label": "HR"},
    {"text": "how do i sign up for 401k", "label": "HR"},
    {"text": "what is the vesting schedule for 401k", "label": "HR"},
    {"text": "am i vested in my 401k immediately", "label": "HR"},
    {"text": "can i take a loan from my 401k", "label": "HR"},
    {"text": "what are the 401k contribution limits", "label": "HR"},
    {"text": "should i do traditional or roth 401k", "label": "HR"},
    {"text": "what investment options are available in 401k", "label": "HR"},
    {"text": "how do i change my 401k contribution", "label": "HR"},
    {"text": "can i roll over my old 401k", "label": "HR"},
    {"text": "what happens to my 401k if i leave", "label": "HR"},
    {"text": "who do i contact about retirement planning", "label": "HR"},
    {"text": "is there life insurance", "label": "HR"},
    {"text": "how much life insurance coverage do i have", "label": "HR"},
    {"text": "can i buy additional life insurance", "label": "HR"},
    {"text": "does the company offer disability insurance", "label": "HR"},
    {"text": "what is short term disability", "label": "HR"},
    {"text": "how long does short term disability last", "label": "HR"},
    {"text": "what percentage of salary does disability pay", "label": "HR"},
    {"text": "how do i file a disability claim", "label": "HR"},
    {"text": "can i work remotely", "label": "HR"},
    {"text": "what is the remote work policy", "label": "HR"},
    {"text": "how many days can i work from home", "label": "HR"},
    {"text": "do i need approval to work remotely", "label": "HR"},
    {"text": "whats the hybrid work schedule", "label": "HR"},
    {"text": "how many days do i need to be in office", "label": "HR"},
    {"text": "can i work from anywhere", "label": "HR"},
    {"text": "what equipment do i get for remote work", "label": "HR"},
    {"text": "is there a home office stipend", "label": "HR"},
    {"text": "can i expense my internet for remote work", "label": "HR"},
    {"text": "what are the expectations for remote workers", "label": "HR"},
    {"text": "do i need to be available during specific hours when remote", "label": "HR"},
    {"text": "can i travel while working remotely", "label": "HR"},
    {"text": "what is the dress code", "label": "HR"},
    {"text": "can i wear jeans to work", "label": "HR"},
    {"text": "is there a casual friday", "label": "HR"},
    {"text": "what should i wear to client meetings", "label": "HR"},
    {"text": "are sneakers allowed", "label": "HR"},
    {"text": "whats business casual here", "label": "HR"},
    {"text": "can i wear shorts in the summer", "label": "HR"},
    {"text": "is there a formal dress code policy", "label": "HR"},
    {"text": "where can i find the employee handbook", "label": "HR"},
    {"text": "what is the code of conduct", "label": "HR"},
    {"text": "what are the company policies", "label": "HR"},
    {"text": "is there a harassment policy", "label": "HR"},
    {"text": "how do i report harassment", "label": "HR"},
    {"text": "what is the ethics hotline number", "label": "HR"},
    {"text": "can i have a side job", "label": "HR"},
    {"text": "what is the outside employment policy", "label": "HR"},
    {"text": "do i need to disclose freelance work", "label": "HR"},
    {"text": "what is the social media policy", "label": "HR"},
    {"text": "can i post about work on social media", "label": "HR"},
    {"text": "am i allowed to drink alcohol at work events", "label": "HR"},
    {"text": "what is the substance abuse policy", "label": "HR"},
    {"text": "can i bring my dog to work", "label": "HR"},
    {"text": "are pets allowed in the office", "label": "HR"},
    {"text": "what is the visitor policy", "label": "HR"},
    {"text": "can my family visit the office", "label": "HR"},
    {"text": "how do i refer someone for a job", "label": "HR"},
    {"text": "is there a referral bonus", "label": "HR"},
    {"text": "how much is the employee referral bonus", "label": "HR"},
    {"text": "what is the performance review process", "label": "HR"},
    {"text": "when are performance reviews", "label": "HR"},
    {"text": "how often do we have one on ones", "label": "HR"},
    {"text": "what are okrs", "label": "HR"},
    {"text": "how do i set goals", "label": "HR"},
    {"text": "when do i get a raise", "label": "HR"},
    {"text": "how does the promotion process work", "label": "HR"},
    {"text": "what are the career paths available", "label": "HR"},
    {"text": "is there internal mobility", "label": "HR"},
    {"text": "can i transfer to another department", "label": "HR"},
    {"text": "how long do i need to be in role before transferring", "label": "HR"},
    {"text": "what professional development is offered", "label": "HR"},
    {"text": "is there tuition reimbursement", "label": "HR"},
    {"text": "how much education reimbursement do i get", "label": "HR"},
    {"text": "what is covered under education reimbursement", "label": "HR"},
    {"text": "can i get reimbursed for certifications", "label": "HR"},
    {"text": "how do i apply for tuition reimbursement", "label": "HR"},
    {"text": "do i have to stay if i get tuition reimbursement", "label": "HR"},
    {"text": "what happens if i leave after getting education reimbursement", "label": "HR"},
    {"text": "is there a learning budget", "label": "HR"},
    {"text": "can i take courses on company time", "label": "HR"},
    {"text": "what conferences can i attend", "label": "HR"},
    {"text": "is there mentorship available", "label": "HR"},
    {"text": "how do i find a mentor", "label": "HR"},
    {"text": "what is the gym reimbursement", "label": "HR"},
    {"text": "how much do you reimburse for gym membership", "label": "HR"},
    {"text": "how do i submit gym reimbursement", "label": "HR"},
    {"text": "what counts as eligible gym expenses", "label": "HR"},
    {"text": "can i get reimbursed for yoga classes", "label": "HR"},
    {"text": "does peloton count for gym reimbursement", "label": "HR"},
    {"text": "is the gym reimbursement taxable", "label": "HR"},
    {"text": "when do i get gym reimbursement", "label": "HR"},
    {"text": "what is the employee assistance program", "label": "HR"},
    {"text": "how do i access eap", "label": "HR"},
    {"text": "is eap confidential", "label": "HR"},
    {"text": "does eap cost anything", "label": "HR"},
    {"text": "what services does eap provide", "label": "HR"},
    {"text": "can i get counseling through eap", "label": "HR"},
    {"text": "what wellness programs are available", "label": "HR"},
    {"text": "is there a wellness stipend", "label": "HR"},
    {"text": "do we get stock options", "label": "HR"},
    {"text": "how do stock options work", "label": "HR"},
    {"text": "what is the vesting schedule for stock", "label": "HR"},
    {"text": "when do my rsus vest", "label": "HR"},
    {"text": "how are bonuses calculated", "label": "HR"},
    {"text": "when do we get bonuses", "label": "HR"},
    {"text": "is there an annual bonus", "label": "HR"},
    {"text": "what is the commuter benefits program", "label": "HR"},
    {"text": "can i get pre tax parking", "label": "HR"},
    {"text": "how do i sign up for commuter benefits", "label": "HR"},
    {"text": "is there a transportation stipend", "label": "HR"},
    {"text": "do you offer childcare assistance", "label": "HR"},
    {"text": "is there backup childcare", "label": "HR"},
    {"text": "what is dependent care fsa", "label": "HR"},
    {"text": "how much can i contribute to dependent care fsa", "label": "HR"},
    {"text": "can i use fsa for daycare", "label": "HR"},
    {"text": "what is a flexible spending account", "label": "HR"},
    {"text": "how does fsa work", "label": "HR"},
    {"text": "can i have both hsa and fsa", "label": "HR"},
    {"text": "what can i use hsa for", "label": "HR"},
    {"text": "does the company contribute to hsa", "label": "HR"},
    {"text": "how do i access my pay stubs", "label": "HR"},
    {"text": "where can i see my w2", "label": "HR"},
    {"text": "when do w2s come out", "label": "HR"},
    {"text": "how do i update my direct deposit", "label": "HR"},
    {"text": "how do i change my address", "label": "HR"},
    {"text": "where do i update my tax withholdings", "label": "HR"},
    {"text": "how do i change my w4", "label": "HR"},
    {"text": "who do i contact for payroll questions", "label": "HR"},
    {"text": "when is payday", "label": "HR"},
    {"text": "how often do we get paid", "label": "HR"},
    {"text": "what if theres an error on my paycheck", "label": "HR"},
    {"text": "how do i update my emergency contact", "label": "HR"},
    {"text": "where do i add my beneficiaries", "label": "HR"},
    {"text": "how do i change my benefits", "label": "HR"},
    {"text": "what is a qualifying life event", "label": "HR"},
    {"text": "can i change benefits mid year", "label": "HR"},
    {"text": "when is open enrollment", "label": "HR"},
    {"text": "how long is open enrollment period", "label": "HR"},
    {"text": "what happens if i miss open enrollment", "label": "HR"},
    {"text": "can i waive health insurance", "label": "HR"},
    {"text": "what if i have insurance through my spouse", "label": "HR"},
    {"text": "do i need to provide proof of other coverage", "label": "HR"},
    {"text": "what is cobra", "label": "HR"},
    {"text": "how long does cobra last", "label": "HR"},
    {"text": "how much does cobra cost", "label": "HR"},
    {"text": "what happens to my benefits if i get terminated", "label": "HR"},
    {"text": "do benefits continue during leave of absence", "label": "HR"},
    {"text": "what is fmla", "label": "HR"},
    {"text": "am i eligible for fmla", "label": "HR"},
    {"text": "how long is fmla leave", "label": "HR"},
    {"text": "is fmla paid or unpaid", "label": "HR"},
    {"text": "how do i request fmla", "label": "HR"},
    {"text": "can i take intermittent fmla", "label": "HR"},
    {"text": "what is medical leave", "label": "HR"},
    {"text": "how do i request a leave of absence", "label": "HR"},
    {"text": "is there paid medical leave", "label": "HR"},
    {"text": "can i take unpaid time off", "label": "HR"},
    {"text": "what is a sabbatical", "label": "HR"},
    {"text": "does the company offer sabbaticals", "label": "HR"},
    {"text": "how do i request a sabbatical", "label": "HR"},
    {"text": "is there volunteer time off", "label": "HR"},
    {"text": "how many volunteer days do i get", "label": "HR"},
    {"text": "can i volunteer during work hours", "label": "HR"},
    {"text": "what is the bereavement policy", "label": "HR"},
    {"text": "how much bereavement leave do i get", "label": "HR"},
    {"text": "is bereavement leave paid", "label": "HR"},
    {"text": "who qualifies for bereavement leave", "label": "HR"},
    {"text": "what is jury duty policy", "label": "HR"},
    {"text": "do i get paid for jury duty", "label": "HR"},
    {"text": "how do i report jury duty", "label": "HR"},
    {"text": "what happens if i get called for jury duty", "label": "HR"},
    {"text": "is there military leave", "label": "HR"},
    {"text": "what are my rights if im called to active duty", "label": "HR"},
    {"text": "how does voting time off work", "label": "HR"},
    {"text": "do i get time off to vote", "label": "HR"},
    {"text": "what is the resignation process", "label": "HR"},
    {"text": "how much notice do i need to give", "label": "HR"},
    {"text": "do i need to give two weeks notice", "label": "HR"},
    {"text": "what happens to my pto when i quit", "label": "HR"},
    {"text": "will i get paid out for unused vacation", "label": "HR"},
    {"text": "how do i resign", "label": "HR"},
    {"text": "who do i tell if im resigning", "label": "HR"},
    {"text": "what is the exit interview process", "label": "HR"},
    {"text": "do i have to do an exit interview", "label": "HR"},
    {"text": "when do i get my final paycheck", "label": "HR"},
    {"text": "what equipment do i return when i leave", "label": "HR"},
    {"text": "how do i return my laptop", "label": "HR"},
    {"text": "what is at will employment", "label": "HR"},
    {"text": "can i be fired without cause", "label": "HR"},
    {"text": "what is the termination policy", "label": "HR"},
    {"text": "what happens if i get laid off", "label": "HR"},
    {"text": "is there severance pay", "label": "HR"},
    {"text": "how much severance do i get", "label": "HR"},
    {"text": "what is a pip", "label": "HR"},
    {"text": "what happens during a performance improvement plan", "label": "HR"},
    {"text": "how long does a pip last", "label": "HR"},
    {"text": "can i be fired during probation period", "label": "HR"},
    {"text": "how long is the probation period", "label": "HR"},
    {"text": "what is the probationary period", "label": "HR"},
    {"text": "am i eligible for benefits during probation", "label": "HR"},
    {"text": "what is the equal employment opportunity policy", "label": "HR"},
    {"text": "is there discrimination protection", "label": "HR"},
    {"text": "how do i report discrimination", "label": "HR"},
    {"text": "what is the diversity policy", "label": "HR"},
    {"text": "are there employee resource groups", "label": "HR"},
    {"text": "what ergs are available", "label": "HR"},
    {"text": "how do i join an erg", "label": "HR"},
    {"text": "is there a women in tech group", "label": "HR"},
    {"text": "what dei initiatives does the company have", "label": "HR"},
    {"text": "is there unconscious bias training", "label": "HR"},
    {"text": "what training is required", "label": "HR"},
    {"text": "do i need to complete compliance training", "label": "HR"},
    {"text": "when is the compliance training deadline", "label": "HR"},
    {"text": "what is the anti harassment training", "label": "HR"},
    {"text": "how long does security training take", "label": "HR"},
    {"text": "where do i find required training", "label": "HR"},
    {"text": "what is the learning management system", "label": "HR"},
    {"text": "how do i access the lms", "label": "HR"},
    {"text": "are there linkedin learning courses", "label": "HR"},
    {"text": "can i take online courses", "label": "HR"},
    {"text": "what is the background check policy", "label": "HR"},
    {"text": "do you do background checks", "label": "HR"},
    {"text": "what shows up on background check", "label": "HR"},
    {"text": "how long does background check take", "label": "HR"},
    {"text": "what is the drug testing policy", "label": "HR"},
    {"text": "do you drug test", "label": "HR"},
    {"text": "when do you drug test", "label": "HR"},
    {"text": "is there random drug testing", "label": "HR"},
    {"text": "what is the confidentiality policy", "label": "HR"},
    {"text": "do i need to sign an nda", "label": "HR"},
    {"text": "what is the non disclosure agreement", "label": "HR"},
    {"text": "what is intellectual property policy", "label": "HR"},
    {"text": "who owns the code i write", "label": "HR"},
    {"text": "can i work on personal projects", "label": "HR"},
    {"text": "what is the moonlighting policy", "label": "HR"},
    {"text": "can i have two jobs", "label": "HR"},
    {"text": "do i need approval for consulting work", "label": "HR"},
    {"text": "what is the conflict of interest policy", "label": "HR"},
    {"text": "how do i report a conflict of interest", "label": "HR"},
    {"text": "can i invest in competitors", "label": "HR"},
    {"text": "what is the workplace safety policy", "label": "HR"},
    {"text": "how do i report a safety concern", "label": "HR"},
    {"text": "what do i do in an emergency", "label": "HR"},
    {"text": "where are the emergency exits", "label": "HR"},
    {"text": "what is the evacuation procedure", "label": "HR"},
    {"text": "who are the fire wardens", "label": "HR"},
    {"text": "is there first aid training", "label": "HR"},
    {"text": "where is the first aid kit", "label": "HR"},
    {"text": "what is the ergonomics policy", "label": "HR"},
    {"text": "can i get a standing desk", "label": "HR"},
    {"text": "how do i request ergonomic equipment", "label": "HR"},
    {"text": "is there a workplace accommodation process", "label": "HR"},
    {"text": "how do i request disability accommodation", "label": "HR"},
    {"text": "what is the ada policy", "label": "HR"},
    {"text": "can i bring a service animal to work", "label": "HR"},
    {"text": "is the office wheelchair accessible", "label": "HR"},
    {"text": "what lactation rooms are available", "label": "HR"},
    {"text": "where can i pump at work", "label": "HR"},
    {"text": "is there a mothers room", "label": "HR"},
    {"text": "what lactation support is provided", "label": "HR"},
    {"text": "can i get a breast pump", "label": "HR"},
    {"text": "how long can i take for pumping breaks", "label": "HR"},
    
    # ENGINEERING QUESTIONS (~300)
    {"text": "how do i create a pull request", "label": "ENGINEERING"},
    {"text": "what is the code review process", "label": "ENGINEERING"},
    {"text": "how many approvals do i need for a pr", "label": "ENGINEERING"},
    {"text": "who reviews my code", "label": "ENGINEERING"},
    {"text": "how long does code review take", "label": "ENGINEERING"},
    {"text": "what is the pr template", "label": "ENGINEERING"},
    {"text": "how do i request a code review", "label": "ENGINEERING"},
    {"text": "what should i include in a pull request", "label": "ENGINEERING"},
    {"text": "can i merge my own pr", "label": "ENGINEERING"},
    {"text": "how do i respond to code review feedback", "label": "ENGINEERING"},
    {"text": "what is the git workflow", "label": "ENGINEERING"},
    {"text": "how do i create a feature branch", "label": "ENGINEERING"},
    {"text": "what branch should i branch from", "label": "ENGINEERING"},
    {"text": "how do i name my branch", "label": "ENGINEERING"},
    {"text": "what is the branching strategy", "label": "ENGINEERING"},
    {"text": "can i force push", "label": "ENGINEERING"},
    {"text": "when should i rebase vs merge", "label": "ENGINEERING"},
    {"text": "how do i rebase my branch", "label": "ENGINEERING"},
    {"text": "what is the difference between develop and main", "label": "ENGINEERING"},
    {"text": "how do i merge to main", "label": "ENGINEERING"},
    {"text": "what is a hotfix branch", "label": "ENGINEERING"},
    {"text": "how do i create a hotfix", "label": "ENGINEERING"},
    {"text": "what is a release branch", "label": "ENGINEERING"},
    {"text": "how do i create a release", "label": "ENGINEERING"},
    {"text": "how often should i rebase", "label": "ENGINEERING"},
    {"text": "what is the commit message format", "label": "ENGINEERING"},
    {"text": "how should i write commit messages", "label": "ENGINEERING"},
    {"text": "do i need to link jira tickets in commits", "label": "ENGINEERING"},
    {"text": "should i sign my commits", "label": "ENGINEERING"},
    {"text": "how do i sign commits with gpg", "label": "ENGINEERING"},
    {"text": "what goes in gitignore", "label": "ENGINEERING"},
    {"text": "can i commit directly to main", "label": "ENGINEERING"},
    {"text": "what branches are protected", "label": "ENGINEERING"},
    {"text": "how do i deploy to production", "label": "ENGINEERING"},
    {"text": "what is the deployment process", "label": "ENGINEERING"},
    {"text": "how do i deploy to staging", "label": "ENGINEERING"},
    {"text": "when does staging auto deploy", "label": "ENGINEERING"},
    {"text": "how do i approve a production deployment", "label": "ENGINEERING"},
    {"text": "what is the deployment pipeline", "label": "ENGINEERING"},
    {"text": "how does ci cd work", "label": "ENGINEERING"},
    {"text": "what is the cicd pipeline", "label": "ENGINEERING"},
    {"text": "how long does deployment take", "label": "ENGINEERING"},
    {"text": "what is blue green deployment", "label": "ENGINEERING"},
    {"text": "how do i rollback a deployment", "label": "ENGINEERING"},
    {"text": "what happens if deployment fails", "label": "ENGINEERING"},
    {"text": "how do i monitor a deployment", "label": "ENGINEERING"},
    {"text": "what is the deployment checklist", "label": "ENGINEERING"},
    {"text": "do i need approval to deploy", "label": "ENGINEERING"},
    {"text": "who approves production deployments", "label": "ENGINEERING"},
    {"text": "how do i deploy a hotfix", "label": "ENGINEERING"},
    {"text": "what is the emergency deployment process", "label": "ENGINEERING"},
    {"text": "can i deploy on friday", "label": "ENGINEERING"},
    {"text": "what are the deployment windows", "label": "ENGINEERING"},
    {"text": "how do i run database migrations", "label": "ENGINEERING"},
    {"text": "what is the migration process", "label": "ENGINEERING"},
    {"text": "should migrations be backwards compatible", "label": "ENGINEERING"},
    {"text": "how do i test migrations", "label": "ENGINEERING"},
    {"text": "what happens if a migration fails", "label": "ENGINEERING"},
    {"text": "can i delete columns immediately", "label": "ENGINEERING"},
    {"text": "how do i rollback a migration", "label": "ENGINEERING"},
    {"text": "what is the on call rotation", "label": "ENGINEERING"},
    {"text": "when am i on call", "label": "ENGINEERING"},
    {"text": "how long is the on call shift", "label": "ENGINEERING"},
    {"text": "what do i do when on call", "label": "ENGINEERING"},
    {"text": "how do i acknowledge a pagerduty alert", "label": "ENGINEERING"},
    {"text": "who is the secondary on call", "label": "ENGINEERING"},
    {"text": "when should i escalate an incident", "label": "ENGINEERING"},
    {"text": "what is a sev 1 incident", "label": "ENGINEERING"},
    {"text": "how do i declare an incident", "label": "ENGINEERING"},
    {"text": "what is the incident response process", "label": "ENGINEERING"},
    {"text": "how often do i update during an incident", "label": "ENGINEERING"},
    {"text": "what is a post mortem", "label": "ENGINEERING"},
    {"text": "how do i write a postmortem", "label": "ENGINEERING"},
    {"text": "when is the postmortem due", "label": "ENGINEERING"},
    {"text": "do i get paid extra for on call", "label": "ENGINEERING"},
    {"text": "what is the on call compensation", "label": "ENGINEERING"},
    {"text": "can i swap on call shifts", "label": "ENGINEERING"},
    {"text": "how do i trade on call with someone", "label": "ENGINEERING"},
    {"text": "what if i cant be on call", "label": "ENGINEERING"},
    {"text": "what is our tech stack", "label": "ENGINEERING"},
    {"text": "what language do we use", "label": "ENGINEERING"},
    {"text": "do we use python or node", "label": "ENGINEERING"},
    {"text": "what version of python do we use", "label": "ENGINEERING"},
    {"text": "what framework do we use for backend", "label": "ENGINEERING"},
    {"text": "is this a django or flask shop", "label": "ENGINEERING"},
    {"text": "what do we use for frontend", "label": "ENGINEERING"},
    {"text": "do we use react or vue", "label": "ENGINEERING"},
    {"text": "what is our database", "label": "ENGINEERING"},
    {"text": "do we use postgres or mysql", "label": "ENGINEERING"},
    {"text": "what do we use for caching", "label": "ENGINEERING"},
    {"text": "do we use redis", "label": "ENGINEERING"},
    {"text": "what cloud provider do we use", "label": "ENGINEERING"},
    {"text": "are we on aws or gcp", "label": "ENGINEERING"},
    {"text": "what aws services do we use", "label": "ENGINEERING"},
    {"text": "how do we do container orchestration", "label": "ENGINEERING"},
    {"text": "do we use kubernetes or ecs", "label": "ENGINEERING"},
    {"text": "what is our infrastructure setup", "label": "ENGINEERING"},
    {"text": "do we use terraform", "label": "ENGINEERING"},
    {"text": "what is iac", "label": "ENGINEERING"},
    {"text": "how do we manage infrastructure", "label": "ENGINEERING"},
    {"text": "what monitoring tools do we use", "label": "ENGINEERING"},
    {"text": "do we use datadog", "label": "ENGINEERING"},
    {"text": "how do i access datadog", "label": "ENGINEERING"},
    {"text": "what is our logging solution", "label": "ENGINEERING"},
    {"text": "where do i find logs", "label": "ENGINEERING"},
    {"text": "how do i check cloudwatch logs", "label": "ENGINEERING"},
    {"text": "what is sentry", "label": "ENGINEERING"},
    {"text": "how do i track errors", "label": "ENGINEERING"},
    {"text": "where do i see error tracking", "label": "ENGINEERING"},
    {"text": "what is our ci tool", "label": "ENGINEERING"},
    {"text": "do we use circleci or github actions", "label": "ENGINEERING"},
    {"text": "how do i run tests", "label": "ENGINEERING"},
    {"text": "what is the test command", "label": "ENGINEERING"},
    {"text": "how do i run unit tests", "label": "ENGINEERING"},
    {"text": "what is our test coverage target", "label": "ENGINEERING"},
    {"text": "how do i check test coverage", "label": "ENGINEERING"},
    {"text": "what testing framework do we use", "label": "ENGINEERING"},
    {"text": "do we use pytest or unittest", "label": "ENGINEERING"},
    {"text": "how do i write integration tests", "label": "ENGINEERING"},
    {"text": "what are e2e tests", "label": "ENGINEERING"},
    {"text": "do we have end to end tests", "label": "ENGINEERING"},
    {"text": "how do i run cypress tests", "label": "ENGINEERING"},
    {"text": "what is the test pyramid", "label": "ENGINEERING"},
    {"text": "should i write tests before or after code", "label": "ENGINEERING"},
    {"text": "what is tdd", "label": "ENGINEERING"},
    {"text": "do we do test driven development", "label": "ENGINEERING"},
    {"text": "how many tests should i write", "label": "ENGINEERING"},
    {"text": "what makes a good test", "label": "ENGINEERING"},
    {"text": "how do i mock dependencies", "label": "ENGINEERING"},
    {"text": "what mocking library do we use", "label": "ENGINEERING"},
    {"text": "how do i test api endpoints", "label": "ENGINEERING"},
    {"text": "what is our api documentation", "label": "ENGINEERING"},
    {"text": "where can i find api docs", "label": "ENGINEERING"},
    {"text": "do we use swagger", "label": "ENGINEERING"},
    {"text": "what is openapi", "label": "ENGINEERING"},
    {"text": "how do i document an api", "label": "ENGINEERING"},
    {"text": "what should be in api documentation", "label": "ENGINEERING"},
    {"text": "how do i test apis locally", "label": "ENGINEERING"},
    {"text": "what is postman", "label": "ENGINEERING"},
    {"text": "can i use postman for testing", "label": "ENGINEERING"},
    {"text": "how do i call internal apis", "label": "ENGINEERING"},
    {"text": "what is rest", "label": "ENGINEERING"},
    {"text": "do we use rest or graphql", "label": "ENGINEERING"},
    {"text": "what is our api versioning strategy", "label": "ENGINEERING"},
    {"text": "how do i version apis", "label": "ENGINEERING"},
    {"text": "what is api rate limiting", "label": "ENGINEERING"},
    {"text": "how many api calls can i make", "label": "ENGINEERING"},
    {"text": "what is the rate limit", "label": "ENGINEERING"},
    {"text": "how do we handle authentication", "label": "ENGINEERING"},
    {"text": "what auth system do we use", "label": "ENGINEERING"},
    {"text": "do we use oauth", "label": "ENGINEERING"},
    {"text": "how do jwt tokens work", "label": "ENGINEERING"},
    {"text": "how long do access tokens last", "label": "ENGINEERING"},
    {"text": "what is refresh token rotation", "label": "ENGINEERING"},
    {"text": "how do we do authorization", "label": "ENGINEERING"},
    {"text": "what is rbac", "label": "ENGINEERING"},
    {"text": "how do roles and permissions work", "label": "ENGINEERING"},
    {"text": "what is our code style guide", "label": "ENGINEERING"},
    {"text": "what linter do we use", "label": "ENGINEERING"},
    {"text": "how do i run the linter", "label": "ENGINEERING"},
    {"text": "what is black formatter", "label": "ENGINEERING"},
    {"text": "how do i format my code", "label": "ENGINEERING"},
    {"text": "what is the line length limit", "label": "ENGINEERING"},
    {"text": "do we use type hints", "label": "ENGINEERING"},
    {"text": "what is mypy", "label": "ENGINEERING"},
    {"text": "how do i run type checking", "label": "ENGINEERING"},
    {"text": "what are our coding standards", "label": "ENGINEERING"},
    {"text": "do we follow pep 8", "label": "ENGINEERING"},
    {"text": "what naming conventions do we use", "label": "ENGINEERING"},
    {"text": "should i use camelcase or snake_case", "label": "ENGINEERING"},
    {"text": "how do i name variables", "label": "ENGINEERING"},
    {"text": "what are best practices for naming", "label": "ENGINEERING"},
    {"text": "should i comment my code", "label": "ENGINEERING"},
    {"text": "how much should i comment", "label": "ENGINEERING"},
    {"text": "what is a docstring", "label": "ENGINEERING"},
    {"text": "how do i write docstrings", "label": "ENGINEERING"},
    {"text": "what docstring format do we use", "label": "ENGINEERING"},
    {"text": "should i document every function", "label": "ENGINEERING"},
    {"text": "what goes in code documentation", "label": "ENGINEERING"},
    {"text": "how do i document complex logic", "label": "ENGINEERING"},
    {"text": "what is the project structure", "label": "ENGINEERING"},
    {"text": "where do i put my code", "label": "ENGINEERING"},
    {"text": "how is the codebase organized", "label": "ENGINEERING"},
    {"text": "what goes in the apps folder", "label": "ENGINEERING"},
    {"text": "where do i add new models", "label": "ENGINEERING"},
    {"text": "how do i create a new app", "label": "ENGINEERING"},
    {"text": "what is the backend folder structure", "label": "ENGINEERING"},
    {"text": "where do tests go", "label": "ENGINEERING"},
    {"text": "how should i organize my tests", "label": "ENGINEERING"},
    {"text": "what is the frontend structure", "label": "ENGINEERING"},
    {"text": "where do components go", "label": "ENGINEERING"},
    {"text": "how big should components be", "label": "ENGINEERING"},
    {"text": "should i use class or functional components", "label": "ENGINEERING"},
    {"text": "what is our react version", "label": "ENGINEERING"},
    {"text": "do we use hooks", "label": "ENGINEERING"},
    {"text": "what is redux toolkit", "label": "ENGINEERING"},
    {"text": "how do we manage state", "label": "ENGINEERING"},
    {"text": "should i use redux or context", "label": "ENGINEERING"},
    {"text": "what is react query", "label": "ENGINEERING"},
    {"text": "how do i fetch data in react", "label": "ENGINEERING"},
    {"text": "what css framework do we use", "label": "ENGINEERING"},
    {"text": "do we use tailwind", "label": "ENGINEERING"},
    {"text": "how do i style components", "label": "ENGINEERING"},
    {"text": "can i use inline styles", "label": "ENGINEERING"},
    {"text": "what is our design system", "label": "ENGINEERING"},
    {"text": "where are the ui components", "label": "ENGINEERING"},
    {"text": "how do i use the component library", "label": "ENGINEERING"},
    {"text": "what is storybook", "label": "ENGINEERING"},
    {"text": "how do i add to storybook", "label": "ENGINEERING"},
    {"text": "how do i set up my local environment", "label": "ENGINEERING"},
    {"text": "what do i need installed locally", "label": "ENGINEERING"},
    {"text": "how do i run the app locally", "label": "ENGINEERING"},
    {"text": "what is the local setup process", "label": "ENGINEERING"},
    {"text": "how do i install dependencies", "label": "ENGINEERING"},
    {"text": "what is npm install", "label": "ENGINEERING"},
    {"text": "should i use npm or yarn", "label": "ENGINEERING"},
    {"text": "how do i run the dev server", "label": "ENGINEERING"},
    {"text": "what port does the app run on", "label": "ENGINEERING"},
    {"text": "how do i access the local database", "label": "ENGINEERING"},
    {"text": "how do i seed the database", "label": "ENGINEERING"},
    {"text": "is there test data", "label": "ENGINEERING"},
    {"text": "how do i get sample data", "label": "ENGINEERING"},
    {"text": "what environment variables do i need", "label": "ENGINEERING"},
    {"text": "where do env vars go", "label": "ENGINEERING"},
    {"text": "how do i set up dotenv", "label": "ENGINEERING"},
    {"text": "what goes in the env file", "label": "ENGINEERING"},
    {"text": "should i commit env files", "label": "ENGINEERING"},
    {"text": "where do i find api keys", "label": "ENGINEERING"},
    {"text": "how do i get aws credentials", "label": "ENGINEERING"},
    {"text": "what is the vpn", "label": "ENGINEERING"},
    {"text": "do i need vpn for development", "label": "ENGINEERING"},
    {"text": "how do i connect to vpn", "label": "ENGINEERING"},
    {"text": "what is docker", "label": "ENGINEERING"},
    {"text": "do we use docker for local dev", "label": "ENGINEERING"},
    {"text": "how do i run docker compose", "label": "ENGINEERING"},
    {"text": "what containers do i need running", "label": "ENGINEERING"},
    {"text": "how do i debug locally", "label": "ENGINEERING"},
    {"text": "what debugger should i use", "label": "ENGINEERING"},
    {"text": "how do i set breakpoints", "label": "ENGINEERING"},
    {"text": "can i use print statements for debugging", "label": "ENGINEERING"},
    {"text": "what logging should i use", "label": "ENGINEERING"},
    {"text": "how do i add logging", "label": "ENGINEERING"},
    {"text": "what log level should i use", "label": "ENGINEERING"},
    {"text": "how verbose should logs be", "label": "ENGINEERING"},
    {"text": "should i log pii", "label": "ENGINEERING"},
    {"text": "what shouldnt be logged", "label": "ENGINEERING"},
    {"text": "how do i handle errors", "label": "ENGINEERING"},
    {"text": "what is our error handling strategy", "label": "ENGINEERING"},
    {"text": "should i use try catch everywhere", "label": "ENGINEERING"},
    {"text": "how do i raise exceptions", "label": "ENGINEERING"},
    {"text": "what exceptions should i catch", "label": "ENGINEERING"},
    {"text": "how do i create custom exceptions", "label": "ENGINEERING"},
    {"text": "what is error propagation", "label": "ENGINEERING"},
    {"text": "how do i handle api errors", "label": "ENGINEERING"},
    {"text": "what status codes should i return", "label": "ENGINEERING"},
    {"text": "when do i use 400 vs 500", "label": "ENGINEERING"},
    {"text": "what is a 422 error", "label": "ENGINEERING"},
    {"text": "how do we do input validation", "label": "ENGINEERING"},
    {"text": "what validation library do we use", "label": "ENGINEERING"},
    {"text": "how do i validate form data", "label": "ENGINEERING"},
    {"text": "what is pydantic", "label": "ENGINEERING"},
    {"text": "how do i use pydantic models", "label": "ENGINEERING"},
    {"text": "what is serialization", "label": "ENGINEERING"},
    {"text": "how do i serialize data", "label": "ENGINEERING"},
    {"text": "what is the orm", "label": "ENGINEERING"},
    {"text": "how do i query the database", "label": "ENGINEERING"},
    {"text": "what is django orm", "label": "ENGINEERING"},
    {"text": "how do i write raw sql", "label": "ENGINEERING"},
    {"text": "should i use raw sql or orm", "label": "ENGINEERING"},
    {"text": "how do i optimize database queries", "label": "ENGINEERING"},
    {"text": "what is n+1 query problem", "label": "ENGINEERING"},
    {"text": "how do i avoid n+1 queries", "label": "ENGINEERING"},
    {"text": "what is select_related", "label": "ENGINEERING"},
    {"text": "when should i use prefetch_related", "label": "ENGINEERING"},
    {"text": "how do i add database indexes", "label": "ENGINEERING"},
    {"text": "what fields should be indexed", "label": "ENGINEERING"},
    {"text": "how do i check slow queries", "label": "ENGINEERING"},
    {"text": "what is query performance", "label": "ENGINEERING"},
    {"text": "how do i cache data", "label": "ENGINEERING"},
    {"text": "when should i use caching", "label": "ENGINEERING"},
    {"text": "what is our caching strategy", "label": "ENGINEERING"},
    {"text": "how long should cache ttl be", "label": "ENGINEERING"},
    {"text": "how do i invalidate cache", "label": "ENGINEERING"},
    {"text": "what is cache stampede", "label": "ENGINEERING"},
    {"text": "how do we handle cache warming", "label": "ENGINEERING"},
    {"text": "what is redis used for", "label": "ENGINEERING"},
    {"text": "how do i use redis", "label": "ENGINEERING"},
    {"text": "what data structures does redis support", "label": "ENGINEERING"},
    {"text": "how do background jobs work", "label": "ENGINEERING"},
    {"text": "what is celery", "label": "ENGINEERING"},
    {"text": "how do i create a celery task", "label": "ENGINEERING"},
    {"text": "when should i use async tasks", "label": "ENGINEERING"},
    {"text": "how do i schedule recurring tasks", "label": "ENGINEERING"},
    {"text": "what is celery beat", "label": "ENGINEERING"},
    {"text": "how do i monitor celery tasks", "label": "ENGINEERING"},
    {"text": "what happens if a task fails", "label": "ENGINEERING"},
    {"text": "how do i retry failed tasks", "label": "ENGINEERING"},
    {"text": "what is our security policy", "label": "ENGINEERING"},
    {"text": "how do i prevent sql injection", "label": "ENGINEERING"},
    {"text": "what is xss", "label": "ENGINEERING"},
    {"text": "how do i prevent cross site scripting", "label": "ENGINEERING"},
    {"text": "what is csrf", "label": "ENGINEERING"},
    {"text": "how do we handle csrf tokens", "label": "ENGINEERING"},
    {"text": "should i sanitize user input", "label": "ENGINEERING"},
    {"text": "how do i validate user input securely", "label": "ENGINEERING"},
    {"text": "what is our password policy", "label": "ENGINEERING"},
    {"text": "how should i hash passwords", "label": "ENGINEERING"},
    {"text": "what is bcrypt", "label": "ENGINEERING"},
    {"text": "how many salt rounds for bcrypt", "label": "ENGINEERING"},
    {"text": "should i store passwords in plain text", "label": "ENGINEERING"},
    {"text": "how do i encrypt sensitive data", "label": "ENGINEERING"},
    {"text": "what encryption should i use", "label": "ENGINEERING"},
    {"text": "what is aes 256", "label": "ENGINEERING"},
    {"text": "how do we manage secrets", "label": "ENGINEERING"},
    {"text": "where do secrets go", "label": "ENGINEERING"},
    {"text": "what is aws secrets manager", "label": "ENGINEERING"},
    {"text": "how do i access secrets", "label": "ENGINEERING"},
    {"text": "can i hardcode api keys", "label": "ENGINEERING"},
    {"text": "should secrets be in git", "label": "ENGINEERING"},
    {"text": "how often should secrets rotate", "label": "ENGINEERING"},
    {"text": "what is our performance budget", "label": "ENGINEERING"},
    {"text": "how fast should pages load", "label": "ENGINEERING"},
    {"text": "what is acceptable api latency", "label": "ENGINEERING"},
    {"text": "how do i measure performance", "label": "ENGINEERING"},
    {"text": "what is lighthouse score", "label": "ENGINEERING"},
    {"text": "how do i optimize bundle size", "label": "ENGINEERING"},
    {"text": "what is code splitting", "label": "ENGINEERING"},
    {"text": "how do i lazy load components", "label": "ENGINEERING"},
    {"text": "should i optimize images", "label": "ENGINEERING"},
    {"text": "what image format should i use", "label": "ENGINEERING"},
    {"text": "how do i compress images", "label": "ENGINEERING"},
    {"text": "what is webp", "label": "ENGINEERING"},
    {"text": "how do we use cdn", "label": "ENGINEERING"},
    {"text": "what is cloudfront", "label": "ENGINEERING"},
    {"text": "where are static assets hosted", "label": "ENGINEERING"},
    {"text": "how do i access the engineering handbook", "label": "ENGINEERING"},
    
    # FINANCE QUESTIONS (~300)
    {"text": "how do i submit an expense report", "label": "FINANCE"},
    {"text": "where do i submit expenses", "label": "FINANCE"},
    {"text": "what is the expense reimbursement process", "label": "FINANCE"},
    {"text": "how long does expense reimbursement take", "label": "FINANCE"},
    {"text": "when will i get reimbursed", "label": "FINANCE"},
    {"text": "how do i get reimbursed for expenses", "label": "FINANCE"},
    {"text": "what expenses are reimbursable", "label": "FINANCE"},
    {"text": "can i expense lunch", "label": "FINANCE"},
    {"text": "can i expense meals", "label": "FINANCE"},
    {"text": "what meals can i expense", "label": "FINANCE"},
    {"text": "can i expense client dinners", "label": "FINANCE"},
    {"text": "is alcohol reimbursable", "label": "FINANCE"},
    {"text": "can i expense drinks", "label": "FINANCE"},
    {"text": "can i expense coffee", "label": "FINANCE"},
    {"text": "what office supplies are reimbursable", "label": "FINANCE"},
    {"text": "can i buy office supplies", "label": "FINANCE"},
    {"text": "how do i expense office supplies", "label": "FINANCE"},
    {"text": "do i need receipts for expenses", "label": "FINANCE"},
    {"text": "what receipts do i need", "label": "FINANCE"},
    {"text": "what if i lost my receipt", "label": "FINANCE"},
    {"text": "can i submit expenses without receipts", "label": "FINANCE"},
    {"text": "how much can i expense without a receipt", "label": "FINANCE"},
    {"text": "what is the receipt threshold", "label": "FINANCE"},
    {"text": "do i need itemized receipts", "label": "FINANCE"},
    {"text": "when do i need to submit expenses", "label": "FINANCE"},
    {"text": "what is the expense submission deadline", "label": "FINANCE"},
    {"text": "how old can expenses be", "label": "FINANCE"},
    {"text": "can i submit old expenses", "label": "FINANCE"},
    {"text": "what happens if i submit expenses late", "label": "FINANCE"},
    {"text": "who approves expenses", "label": "FINANCE"},
    {"text": "does my manager approve expenses", "label": "FINANCE"},
    {"text": "what is the expense approval process", "label": "FINANCE"},
    {"text": "how long does expense approval take", "label": "FINANCE"},
    {"text": "what if my expense is rejected", "label": "FINANCE"},
    {"text": "why was my expense denied", "label": "FINANCE"},
    {"text": "can i resubmit a rejected expense", "label": "FINANCE"},
    {"text": "how do i check expense status", "label": "FINANCE"},
    {"text": "where can i see my expense reports", "label": "FINANCE"},
    {"text": "how do i track my expenses", "label": "FINANCE"},
    {"text": "what is the travel policy", "label": "FINANCE"},
    {"text": "how do i book travel", "label": "FINANCE"},
    {"text": "do i need approval to travel", "label": "FINANCE"},
    {"text": "who approves business travel", "label": "FINANCE"},
    {"text": "how far in advance should i book travel", "label": "FINANCE"},
    {"text": "can i book my own flights", "label": "FINANCE"},
    {"text": "what class can i fly", "label": "FINANCE"},
    {"text": "can i fly business class", "label": "FINANCE"},
    {"text": "when can i fly business class", "label": "FINANCE"},
    {"text": "what is the flight policy", "label": "FINANCE"},
    {"text": "can i use my airline miles", "label": "FINANCE"},
    {"text": "can i keep frequent flyer miles", "label": "FINANCE"},
    {"text": "what baggage fees are covered", "label": "FINANCE"},
    {"text": "can i expense checked bags", "label": "FINANCE"},
    {"text": "what about seat selection fees", "label": "FINANCE"},
    {"text": "can i pay for preferred seating", "label": "FINANCE"},
    {"text": "what hotel can i book", "label": "FINANCE"},
    {"text": "how much can i spend on hotels", "label": "FINANCE"},
    {"text": "what is the hotel rate limit", "label": "FINANCE"},
    {"text": "can i stay at expensive hotels", "label": "FINANCE"},
    {"text": "what is the per night hotel limit", "label": "FINANCE"},
    {"text": "can i book airbnb", "label": "FINANCE"},
    {"text": "is airbnb allowed", "label": "FINANCE"},
    {"text": "can i use vrbo for business travel", "label": "FINANCE"},
    {"text": "what hotel amenities are covered", "label": "FINANCE"},
    {"text": "can i expense hotel wifi", "label": "FINANCE"},
    {"text": "is hotel parking reimbursable", "label": "FINANCE"},
    {"text": "can i expense minibar", "label": "FINANCE"},
    {"text": "are resort fees covered", "label": "FINANCE"},
    {"text": "what is the per diem rate", "label": "FINANCE"},
    {"text": "how much is per diem", "label": "FINANCE"},
    {"text": "what is per diem for meals", "label": "FINANCE"},
    {"text": "how much for breakfast per diem", "label": "FINANCE"},
    {"text": "what is lunch per diem", "label": "FINANCE"},
    {"text": "how much is dinner per diem", "label": "FINANCE"},
    {"text": "can i use per diem instead of receipts", "label": "FINANCE"},
    {"text": "do i need receipts if i take per diem", "label": "FINANCE"},
    {"text": "what is actual expense method", "label": "FINANCE"},
    {"text": "should i use per diem or actual expenses", "label": "FINANCE"},
    {"text": "what is international per diem", "label": "FINANCE"},
    {"text": "how does per diem work for travel days", "label": "FINANCE"},
    {"text": "do i get full per diem on first day", "label": "FINANCE"},
    {"text": "what is the car rental policy", "label": "FINANCE"},
    {"text": "can i rent a car", "label": "FINANCE"},
    {"text": "what size car can i rent", "label": "FINANCE"},
    {"text": "can i rent an suv", "label": "FINANCE"},
    {"text": "what rental car is allowed", "label": "FINANCE"},
    {"text": "should i get rental car insurance", "label": "FINANCE"},
    {"text": "is rental car insurance covered", "label": "FINANCE"},
    {"text": "can i decline rental car insurance", "label": "FINANCE"},
    {"text": "what if i damage the rental car", "label": "FINANCE"},
    {"text": "how do i return the rental car", "label": "FINANCE"},
    {"text": "should i refuel the rental car", "label": "FINANCE"},
    {"text": "can i expense gas", "label": "FINANCE"},
    {"text": "what is the mileage reimbursement rate", "label": "FINANCE"},
    {"text": "how much per mile reimbursement", "label": "FINANCE"},
    {"text": "can i use my personal car for business", "label": "FINANCE"},
    {"text": "how do i calculate mileage", "label": "FINANCE"},
    {"text": "what is reimbursable mileage", "label": "FINANCE"},
    {"text": "can i expense parking", "label": "FINANCE"},
    {"text": "are parking fees reimbursable", "label": "FINANCE"},
    {"text": "can i expense tolls", "label": "FINANCE"},
    {"text": "what about parking tickets", "label": "FINANCE"},
    {"text": "can i expense traffic violations", "label": "FINANCE"},
    {"text": "can i take uber for business", "label": "FINANCE"},
    {"text": "is uber reimbursable", "label": "FINANCE"},
    {"text": "can i expense lyft", "label": "FINANCE"},
    {"text": "what rideshare is allowed", "label": "FINANCE"},
    {"text": "can i take taxi", "label": "FINANCE"},
    {"text": "how much can i tip drivers", "label": "FINANCE"},
    {"text": "is tipping reimbursable", "label": "FINANCE"},
    {"text": "what is a reasonable tip", "label": "FINANCE"},
    {"text": "can i expense public transportation", "label": "FINANCE"},
    {"text": "is subway fare reimbursable", "label": "FINANCE"},
    {"text": "can i expense train tickets", "label": "FINANCE"},
    {"text": "what is the international travel policy", "label": "FINANCE"},
    {"text": "do i need approval for international travel", "label": "FINANCE"},
    {"text": "who approves international trips", "label": "FINANCE"},
    {"text": "can i expense passport fees", "label": "FINANCE"},
    {"text": "are visa fees reimbursable", "label": "FINANCE"},
    {"text": "can i expense travel vaccinations", "label": "FINANCE"},
    {"text": "what about international phone charges", "label": "FINANCE"},
    {"text": "can i expense international data", "label": "FINANCE"},
    {"text": "how do currency exchanges work", "label": "FINANCE"},
    {"text": "what exchange rate do i use", "label": "FINANCE"},
    {"text": "can i use my credit card internationally", "label": "FINANCE"},
    {"text": "what is the corporate card policy", "label": "FINANCE"},
    {"text": "how do i get a corporate credit card", "label": "FINANCE"},
    {"text": "who is eligible for corporate card", "label": "FINANCE"},
    {"text": "what can i use corporate card for", "label": "FINANCE"},
    {"text": "can i use corporate card for personal", "label": "FINANCE"},
    {"text": "what if i accidentally used corporate card", "label": "FINANCE"},
    {"text": "how do i reconcile corporate card", "label": "FINANCE"},
    {"text": "when is corporate card due", "label": "FINANCE"},
    {"text": "what happens if i dont reconcile", "label": "FINANCE"},
    {"text": "can i get cash back on corporate card", "label": "FINANCE"},
    {"text": "what rewards does corporate card have", "label": "FINANCE"},
    {"text": "who pays corporate card bill", "label": "FINANCE"},
    {"text": "what if my corporate card is declined", "label": "FINANCE"},
    {"text": "how do i report lost corporate card", "label": "FINANCE"},
    {"text": "what is my spending limit", "label": "FINANCE"},
    {"text": "is there a card limit", "label": "FINANCE"},
    {"text": "what is the budget approval process", "label": "FINANCE"},
    {"text": "how do i request budget", "label": "FINANCE"},
    {"text": "who approves budgets", "label": "FINANCE"},
    {"text": "what is my approval authority", "label": "FINANCE"},
    {"text": "how much can i approve", "label": "FINANCE"},
    {"text": "what expenses need approval", "label": "FINANCE"},
    {"text": "do i need approval for purchases", "label": "FINANCE"},
    {"text": "what is the approval threshold", "label": "FINANCE"},
    {"text": "how much can i spend without approval", "label": "FINANCE"},
    {"text": "who approves large purchases", "label": "FINANCE"},
    {"text": "what needs cfo approval", "label": "FINANCE"},
    {"text": "when do i need ceo approval", "label": "FINANCE"},
    {"text": "what is a purchase order", "label": "FINANCE"},
    {"text": "do i need a po", "label": "FINANCE"},
    {"text": "how do i create a purchase order", "label": "FINANCE"},
    {"text": "when is a po required", "label": "FINANCE"},
    {"text": "what purchases need a po", "label": "FINANCE"},
    {"text": "can i buy without a po", "label": "FINANCE"},
    {"text": "what is the po process", "label": "FINANCE"},
    {"text": "how long does po approval take", "label": "FINANCE"},
    {"text": "who approves purchase orders", "label": "FINANCE"},
    {"text": "what is a three way match", "label": "FINANCE"},
    {"text": "what is invoice processing", "label": "FINANCE"},
    {"text": "how do invoices get paid", "label": "FINANCE"},
    {"text": "how long until invoices are paid", "label": "FINANCE"},
    {"text": "what is the payment schedule", "label": "FINANCE"},
    {"text": "when do vendors get paid", "label": "FINANCE"},
    {"text": "what are payment terms", "label": "FINANCE"},
    {"text": "what is net 30", "label": "FINANCE"},
    {"text": "what is 2 10 net 30", "label": "FINANCE"},
    {"text": "should we take early payment discounts", "label": "FINANCE"},
    {"text": "how do i add a new vendor", "label": "FINANCE"},
    {"text": "what is vendor setup", "label": "FINANCE"},
    {"text": "what do i need to set up a vendor", "label": "FINANCE"},
    {"text": "how long does vendor setup take", "label": "FINANCE"},
    {"text": "what is a w9 form", "label": "FINANCE"},
    {"text": "do vendors need to provide w9", "label": "FINANCE"},
    {"text": "what vendor information is required", "label": "FINANCE"},
    {"text": "how do i change vendor banking info", "label": "FINANCE"},
    {"text": "what is the vendor payment process", "label": "FINANCE"},
    {"text": "how are vendors paid", "label": "FINANCE"},
    {"text": "do we pay by check or ach", "label": "FINANCE"},
    {"text": "what is ach payment", "label": "FINANCE"},
    {"text": "how long do wire transfers take", "label": "FINANCE"},
    {"text": "what is the wire transfer fee", "label": "FINANCE"},
    {"text": "when should i use wire transfer", "label": "FINANCE"},
    {"text": "what is the budget process", "label": "FINANCE"},
    {"text": "when is budget due", "label": "FINANCE"},
    {"text": "how do i submit my budget", "label": "FINANCE"},
    {"text": "what goes in the budget", "label": "FINANCE"},
    {"text": "what is budget planning", "label": "FINANCE"},
    {"text": "when does budget planning start", "label": "FINANCE"},
    {"text": "what is the fiscal year", "label": "FINANCE"},
    {"text": "when does fiscal year start", "label": "FINANCE"},
    {"text": "how do i track budget", "label": "FINANCE"},
    {"text": "where can i see budget vs actual", "label": "FINANCE"},
    {"text": "what is budget variance", "label": "FINANCE"},
    {"text": "what if im over budget", "label": "FINANCE"},
    {"text": "how do i request additional budget", "label": "FINANCE"},
    {"text": "can i transfer budget between categories", "label": "FINANCE"},
    {"text": "what is a budget amendment", "label": "FINANCE"},
    {"text": "how do i amend my budget", "label": "FINANCE"},
    {"text": "what is contingency budget", "label": "FINANCE"},
    {"text": "how do i access contingency funds", "label": "FINANCE"},
    {"text": "what is capital expenditure", "label": "FINANCE"},
    {"text": "what is capex", "label": "FINANCE"},
    {"text": "how do i request capex", "label": "FINANCE"},
    {"text": "what needs capex approval", "label": "FINANCE"},
    {"text": "what is operating expense", "label": "FINANCE"},
    {"text": "what is opex", "label": "FINANCE"},
    {"text": "whats the difference between capex and opex", "label": "FINANCE"},
    {"text": "what is depreciation", "label": "FINANCE"},
    {"text": "how is depreciation calculated", "label": "FINANCE"},
    {"text": "what is straight line depreciation", "label": "FINANCE"},
    {"text": "what is useful life", "label": "FINANCE"},
    {"text": "how long do we depreciate assets", "label": "FINANCE"},
    {"text": "what is the capitalization threshold", "label": "FINANCE"},
    {"text": "what gets capitalized", "label": "FINANCE"},
    {"text": "when should i capitalize vs expense", "label": "FINANCE"},
    {"text": "what is an asset", "label": "FINANCE"},
    {"text": "how do i record an asset purchase", "label": "FINANCE"},
    {"text": "what is asset tagging", "label": "FINANCE"},
    {"text": "do assets need tags", "label": "FINANCE"},
    {"text": "what is asset tracking", "label": "FINANCE"},
    {"text": "how do i dispose of an asset", "label": "FINANCE"},
    {"text": "what is asset disposal process", "label": "FINANCE"},
    {"text": "who approves asset disposal", "label": "FINANCE"},
    {"text": "what is the petty cash policy", "label": "FINANCE"},
    {"text": "how do i get petty cash", "label": "FINANCE"},
    {"text": "where is petty cash", "label": "FINANCE"},
    {"text": "what can i use petty cash for", "label": "FINANCE"},
    {"text": "how much petty cash can i take", "label": "FINANCE"},
    {"text": "do i need a receipt for petty cash", "label": "FINANCE"},
    {"text": "how do i replenish petty cash", "label": "FINANCE"},
    {"text": "what is cash advance", "label": "FINANCE"},
    {"text": "can i get a cash advance", "label": "FINANCE"},
    {"text": "how do i request cash advance", "label": "FINANCE"},
    {"text": "when should i use cash advance", "label": "FINANCE"},
    {"text": "what is the invoice approval process", "label": "FINANCE"},
    {"text": "how do i approve an invoice", "label": "FINANCE"},
    {"text": "what should i check on invoices", "label": "FINANCE"},
    {"text": "how do i reject an invoice", "label": "FINANCE"},
    {"text": "what if invoice doesnt match po", "label": "FINANCE"},
    {"text": "what is a disputed invoice", "label": "FINANCE"},
    {"text": "how do i dispute an invoice", "label": "FINANCE"},
    {"text": "what happens to disputed invoices", "label": "FINANCE"},
    {"text": "what are payment controls", "label": "FINANCE"},
    {"text": "what is segregation of duties", "label": "FINANCE"},
    {"text": "why cant i approve my own expenses", "label": "FINANCE"},
    {"text": "what is dual authorization", "label": "FINANCE"},
    {"text": "when is dual approval required", "label": "FINANCE"},
    {"text": "what is fraud prevention", "label": "FINANCE"},
    {"text": "how do we prevent fraud", "label": "FINANCE"},
    {"text": "what is positive pay", "label": "FINANCE"},
    {"text": "how do i report suspected fraud", "label": "FINANCE"},
    {"text": "what happens if i see fraud", "label": "FINANCE"},
    {"text": "is there an ethics hotline", "label": "FINANCE"},
    {"text": "what is the month end close", "label": "FINANCE"},
    {"text": "when does month end close", "label": "FINANCE"},
    {"text": "what is the close calendar", "label": "FINANCE"},
    {"text": "when are financials due", "label": "FINANCE"},
    {"text": "what is the close deadline", "label": "FINANCE"},
    {"text": "what is account reconciliation", "label": "FINANCE"},
    {"text": "how do i reconcile my accounts", "label": "FINANCE"},
    {"text": "when are reconciliations due", "label": "FINANCE"},
    {"text": "what is a bank reconciliation", "label": "FINANCE"},
    {"text": "how often do we reconcile", "label": "FINANCE"},
    {"text": "what is a journal entry", "label": "FINANCE"},
    {"text": "how do i post a journal entry", "label": "FINANCE"},
    {"text": "who can post journal entries", "label": "FINANCE"},
    {"text": "what is an accrual", "label": "FINANCE"},
    {"text": "when should i accrue expenses", "label": "FINANCE"},
    {"text": "what is prepaid expense", "label": "FINANCE"},
    {"text": "how do i record prepaid expenses", "label": "FINANCE"},
    {"text": "what is deferred revenue", "label": "FINANCE"},
    {"text": "what is revenue recognition", "label": "FINANCE"},
    {"text": "when do we recognize revenue", "label": "FINANCE"},
    {"text": "what is gaap", "label": "FINANCE"},
    {"text": "do we follow gaap", "label": "FINANCE"},
    {"text": "what accounting standards do we use", "label": "FINANCE"},
    {"text": "what is the chart of accounts", "label": "FINANCE"},
    {"text": "how do i find the right gl account", "label": "FINANCE"},
    {"text": "what gl code should i use", "label": "FINANCE"},
    {"text": "what is a gl account", "label": "FINANCE"},
    {"text": "how do i code expenses", "label": "FINANCE"},
    {"text": "what is the correct cost center", "label": "FINANCE"},
    {"text": "what project code should i use", "label": "FINANCE"},
    {"text": "what is financial reporting", "label": "FINANCE"},
    {"text": "when do financial reports come out", "label": "FINANCE"},
    {"text": "where can i see financial statements", "label": "FINANCE"},
    {"text": "what is on the p&l", "label": "FINANCE"},
    {"text": "what is profit and loss statement", "label": "FINANCE"},
    {"text": "what is the income statement", "label": "FINANCE"},
    {"text": "what is the balance sheet", "label": "FINANCE"},
    {"text": "what is cash flow statement", "label": "FINANCE"},
    {"text": "how do i read financial statements", "label": "FINANCE"},
    {"text": "what are our financial metrics", "label": "FINANCE"},
    {"text": "what kpis do we track", "label": "FINANCE"},
    {"text": "how is the company performing financially", "label": "FINANCE"},
    {"text": "are we profitable", "label": "FINANCE"},
    
    # GENERAL QUESTIONS (~300)
    {"text": "when do i start", "label": "GENERAL"},
    {"text": "what time should i arrive on first day", "label": "GENERAL"},
    {"text": "where do i go on my first day", "label": "GENERAL"},
    {"text": "what should i bring on first day", "label": "GENERAL"},
    {"text": "what happens on my first day", "label": "GENERAL"},
    {"text": "is there an orientation", "label": "GENERAL"},
    {"text": "what is onboarding", "label": "GENERAL"},
    {"text": "how long is onboarding", "label": "GENERAL"},
    {"text": "what happens during onboarding", "label": "GENERAL"},
    {"text": "who do i meet on first day", "label": "GENERAL"},
    {"text": "will i meet my manager on day one", "label": "GENERAL"},
    {"text": "do i get a tour of the office", "label": "GENERAL"},
    {"text": "what equipment will i get", "label": "GENERAL"},
    {"text": "do i get a laptop", "label": "GENERAL"},
    {"text": "what computer will i receive", "label": "GENERAL"},
    {"text": "will i get a monitor", "label": "GENERAL"},
    {"text": "what about a mouse and keyboard", "label": "GENERAL"},
    {"text": "do i get headphones", "label": "GENERAL"},
    {"text": "will i get a phone", "label": "GENERAL"},
    {"text": "what office supplies do i get", "label": "GENERAL"},
    {"text": "can i request additional equipment", "label": "GENERAL"},
    {"text": "how do i get a second monitor", "label": "GENERAL"},
    {"text": "what is the equipment request process", "label": "GENERAL"},
    {"text": "who do i contact for equipment", "label": "GENERAL"},
    {"text": "what is my email address", "label": "GENERAL"},
    {"text": "how do i access my email", "label": "GENERAL"},
    {"text": "what is my username", "label": "GENERAL"},
    {"text": "how do i log in", "label": "GENERAL"},
    {"text": "what is my password", "label": "GENERAL"},
    {"text": "how do i reset my password", "label": "GENERAL"},
    {"text": "i forgot my password", "label": "GENERAL"},
    {"text": "what systems do i need access to", "label": "GENERAL"},
    {"text": "how do i get system access", "label": "GENERAL"},
    {"text": "when will i have access to everything", "label": "GENERAL"},
    {"text": "how long does it take to get access", "label": "GENERAL"},
    {"text": "who sets up my accounts", "label": "GENERAL"},
    {"text": "what is the it helpdesk number", "label": "GENERAL"},
    {"text": "how do i contact it support", "label": "GENERAL"},
    {"text": "what if i have technical issues", "label": "GENERAL"},
    {"text": "my laptop isnt working", "label": "GENERAL"},
    {"text": "i cant log in", "label": "GENERAL"},
    {"text": "where is the it support email", "label": "GENERAL"},
    {"text": "is there it chat support", "label": "GENERAL"},
    {"text": "what are it support hours", "label": "GENERAL"},
    {"text": "is there after hours it support", "label": "GENERAL"},
    {"text": "what is the vpn", "label": "GENERAL"},
    {"text": "how do i connect to vpn", "label": "GENERAL"},
    {"text": "do i need vpn", "label": "GENERAL"},
    {"text": "when should i use vpn", "label": "GENERAL"},
    {"text": "how do i install vpn", "label": "GENERAL"},
    {"text": "what collaboration tools do we use", "label": "GENERAL"},
    {"text": "do we use slack or teams", "label": "GENERAL"},
    {"text": "how do i join slack", "label": "GENERAL"},
    {"text": "what slack channels should i join", "label": "GENERAL"},
    {"text": "is there a general channel", "label": "GENERAL"},
    {"text": "how do i find people on slack", "label": "GENERAL"},
    {"text": "what is zoom", "label": "GENERAL"},
    {"text": "how do i join zoom meetings", "label": "GENERAL"},
    {"text": "do i need to download zoom", "label": "GENERAL"},
    {"text": "what video conferencing do we use", "label": "GENERAL"},
    {"text": "how do i schedule a meeting", "label": "GENERAL"},
    {"text": "what calendar system do we use", "label": "GENERAL"},
    {"text": "do we use google calendar or outlook", "label": "GENERAL"},
    {"text": "how do i share my calendar", "label": "GENERAL"},
    {"text": "where do i park", "label": "GENERAL"},
    {"text": "is there employee parking", "label": "GENERAL"},
    {"text": "how much does parking cost", "label": "GENERAL"},
    {"text": "do i need a parking pass", "label": "GENERAL"},
    {"text": "how do i get a parking pass", "label": "GENERAL"},
    {"text": "where is visitor parking", "label": "GENERAL"},
    {"text": "is parking free", "label": "GENERAL"},
    {"text": "what about street parking", "label": "GENERAL"},
    {"text": "is there a parking garage", "label": "GENERAL"},
    {"text": "how do i get a badge", "label": "GENERAL"},
    {"text": "when will i receive my badge", "label": "GENERAL"},
    {"text": "what is the badge for", "label": "GENERAL"},
    {"text": "do i need my badge every day", "label": "GENERAL"},
    {"text": "what if i forget my badge", "label": "GENERAL"},
    {"text": "i lost my badge", "label": "GENERAL"},
    {"text": "how do i replace my badge", "label": "GENERAL"},
    {"text": "does my badge open all doors", "label": "GENERAL"},
    {"text": "what areas can i access", "label": "GENERAL"},
    {"text": "how do i get access to conference rooms", "label": "GENERAL"},
    {"text": "where is the office located", "label": "GENERAL"},
    {"text": "what is the office address", "label": "GENERAL"},
    {"text": "how do i get to the office", "label": "GENERAL"},
    {"text": "is there public transportation nearby", "label": "GENERAL"},
    {"text": "what is the nearest subway station", "label": "GENERAL"},
    {"text": "is the office near a bus stop", "label": "GENERAL"},
    {"text": "what are office hours", "label": "GENERAL"},
    {"text": "what time does the office open", "label": "GENERAL"},
    {"text": "what time does the office close", "label": "GENERAL"},
    {"text": "do i need to work specific hours", "label": "GENERAL"},
    {"text": "what are core hours", "label": "GENERAL"},
    {"text": "is there flexible scheduling", "label": "GENERAL"},
    {"text": "can i work different hours", "label": "GENERAL"},
    {"text": "where do i sit", "label": "GENERAL"},
    {"text": "do i have an assigned desk", "label": "GENERAL"},
    {"text": "is there hot desking", "label": "GENERAL"},
    {"text": "can i choose my desk", "label": "GENERAL"},
    {"text": "where is my workspace", "label": "GENERAL"},
    {"text": "where are the restrooms", "label": "GENERAL"},
    {"text": "where is the kitchen", "label": "GENERAL"},
    {"text": "where is the break room", "label": "GENERAL"},
    {"text": "is there free coffee", "label": "GENERAL"},
    {"text": "what snacks are available", "label": "GENERAL"},
    {"text": "is there free food", "label": "GENERAL"},
    {"text": "where can i eat lunch", "label": "GENERAL"},
    {"text": "is there a cafeteria", "label": "GENERAL"},
    {"text": "where can i get lunch nearby", "label": "GENERAL"},
    {"text": "what restaurants are close", "label": "GENERAL"},
    {"text": "is there a fridge i can use", "label": "GENERAL"},
    {"text": "can i store food in the fridge", "label": "GENERAL"},
    {"text": "is there a microwave", "label": "GENERAL"},
    {"text": "where are conference rooms", "label": "GENERAL"},
    {"text": "how do i book a conference room", "label": "GENERAL"},
    {"text": "how do i reserve a meeting room", "label": "GENERAL"},
    {"text": "what meeting rooms are available", "label": "GENERAL"},
    {"text": "how far in advance can i book rooms", "label": "GENERAL"},
    {"text": "is there a room booking system", "label": "GENERAL"},
    {"text": "where are the phone booths", "label": "GENERAL"},
    {"text": "are there private call rooms", "label": "GENERAL"},
    {"text": "where can i take a private call", "label": "GENERAL"},
    {"text": "what is the company mission", "label": "GENERAL"},
    {"text": "what are our company values", "label": "GENERAL"},
    {"text": "what does the company do", "label": "GENERAL"},
    {"text": "what products do we make", "label": "GENERAL"},
    {"text": "what services do we offer", "label": "GENERAL"},
    {"text": "who are our customers", "label": "GENERAL"},
    {"text": "who are our competitors", "label": "GENERAL"},
    {"text": "what is our market position", "label": "GENERAL"},
    {"text": "what is the company vision", "label": "GENERAL"},
    {"text": "what are our strategic goals", "label": "GENERAL"},
    {"text": "where can i learn about company history", "label": "GENERAL"},
    {"text": "when was the company founded", "label": "GENERAL"},
    {"text": "who founded the company", "label": "GENERAL"},
    {"text": "how many employees do we have", "label": "GENERAL"},
    {"text": "how big is the company", "label": "GENERAL"},
    {"text": "where are our offices", "label": "GENERAL"},
    {"text": "do we have international offices", "label": "GENERAL"},
    {"text": "what is company culture like", "label": "GENERAL"},
    {"text": "how would you describe the culture", "label": "GENERAL"},
    {"text": "what is it like to work here", "label": "GENERAL"},
    {"text": "is the culture collaborative", "label": "GENERAL"},
    {"text": "what makes this company special", "label": "GENERAL"},
    {"text": "why do people work here", "label": "GENERAL"},
    {"text": "what are company events", "label": "GENERAL"},
    {"text": "are there team building activities", "label": "GENERAL"},
    {"text": "does the company have parties", "label": "GENERAL"},
    {"text": "is there a holiday party", "label": "GENERAL"},
    {"text": "what social events happen", "label": "GENERAL"},
    {"text": "are there happy hours", "label": "GENERAL"},
    {"text": "what is the annual company retreat", "label": "GENERAL"},
    {"text": "who is my manager", "label": "GENERAL"},
    {"text": "how do i contact my manager", "label": "GENERAL"},
    {"text": "what is my managers email", "label": "GENERAL"},
    {"text": "when do i meet with my manager", "label": "GENERAL"},
    {"text": "how often are one on ones", "label": "GENERAL"},
    {"text": "what should i discuss in one on ones", "label": "GENERAL"},
    {"text": "who do i report to", "label": "GENERAL"},
    {"text": "what is the reporting structure", "label": "GENERAL"},
    {"text": "where is the org chart", "label": "GENERAL"},
    {"text": "can i see the organization chart", "label": "GENERAL"},
    {"text": "how is the company organized", "label": "GENERAL"},
    {"text": "what teams are there", "label": "GENERAL"},
    {"text": "what departments exist", "label": "GENERAL"},
    {"text": "who is on my team", "label": "GENERAL"},
    {"text": "how many people on my team", "label": "GENERAL"},
    {"text": "who are my teammates", "label": "GENERAL"},
    {"text": "how do i find coworkers", "label": "GENERAL"},
    {"text": "is there an employee directory", "label": "GENERAL"},
    {"text": "where can i find contact information", "label": "GENERAL"},
    {"text": "how do i look up someone", "label": "GENERAL"},
    {"text": "how do i find peoples email", "label": "GENERAL"},
    {"text": "what is the email format", "label": "GENERAL"},
    {"text": "who is the ceo", "label": "GENERAL"},
    {"text": "who is in leadership", "label": "GENERAL"},
    {"text": "who are the executives", "label": "GENERAL"},
    {"text": "who is the cto", "label": "GENERAL"},
    {"text": "who is the cfo", "label": "GENERAL"},
    {"text": "who runs hr", "label": "GENERAL"},
    {"text": "who is the head of engineering", "label": "GENERAL"},
    {"text": "how do i contact hr", "label": "GENERAL"},
    {"text": "what is the hr email", "label": "GENERAL"},
    {"text": "who do i talk to about hr issues", "label": "GENERAL"},
    {"text": "where is the hr department", "label": "GENERAL"},
    {"text": "what are hr hours", "label": "GENERAL"},
    {"text": "can i schedule time with hr", "label": "GENERAL"},
    {"text": "who is my hr business partner", "label": "GENERAL"},
    {"text": "what does hr help with", "label": "GENERAL"},
    {"text": "who handles payroll", "label": "GENERAL"},
    {"text": "who do i ask about benefits", "label": "GENERAL"},
    {"text": "who handles it requests", "label": "GENERAL"},
    {"text": "who is the it manager", "label": "GENERAL"},
    {"text": "who runs facilities", "label": "GENERAL"},
    {"text": "who is the office manager", "label": "GENERAL"},
    {"text": "who do i contact for office supplies", "label": "GENERAL"},
    {"text": "how do i order supplies", "label": "GENERAL"},
    {"text": "where do i get pens and paper", "label": "GENERAL"},
    {"text": "can i order my own supplies", "label": "GENERAL"},
    {"text": "is there a supply closet", "label": "GENERAL"},
    {"text": "where are office supplies", "label": "GENERAL"},
    {"text": "what is the first week like", "label": "GENERAL"},
    {"text": "what should i expect in week one", "label": "GENERAL"},
    {"text": "what training will i receive", "label": "GENERAL"},
    {"text": "is there new hire training", "label": "GENERAL"},
    {"text": "what courses do i need to take", "label": "GENERAL"},
    {"text": "is training mandatory", "label": "GENERAL"},
    {"text": "when do i complete training", "label": "GENERAL"},
    {"text": "how long does training take", "label": "GENERAL"},
    {"text": "what is the 30 60 90 day plan", "label": "GENERAL"},
    {"text": "what are my goals for first 30 days", "label": "GENERAL"},
    {"text": "what should i accomplish in 90 days", "label": "GENERAL"},
    {"text": "when is my first performance review", "label": "GENERAL"},
    {"text": "is there a 90 day review", "label": "GENERAL"},
    {"text": "what is the probation period", "label": "GENERAL"},
    {"text": "am i on probation", "label": "GENERAL"},
    {"text": "how long is probation", "label": "GENERAL"},
    {"text": "will i have a mentor", "label": "GENERAL"},
    {"text": "do you assign mentors", "label": "GENERAL"},
    {"text": "who is my onboarding buddy", "label": "GENERAL"},
    {"text": "will someone help me get started", "label": "GENERAL"},
    {"text": "who can i ask questions", "label": "GENERAL"},
    {"text": "what if i have questions", "label": "GENERAL"},
    {"text": "who should i go to for help", "label": "GENERAL"},
    {"text": "is it ok to ask questions", "label": "GENERAL"},
    {"text": "what questions should i ask", "label": "GENERAL"},
    {"text": "where can i find information", "label": "GENERAL"},
    {"text": "is there a company wiki", "label": "GENERAL"},
    {"text": "where is documentation", "label": "GENERAL"},
    {"text": "is there a knowledge base", "label": "GENERAL"},
    {"text": "where do i find company policies", "label": "GENERAL"},
    {"text": "where is the employee handbook", "label": "GENERAL"},
    {"text": "how do i access the handbook", "label": "GENERAL"},
    {"text": "what policies should i know", "label": "GENERAL"},
    {"text": "what rules should i be aware of", "label": "GENERAL"},
    {"text": "what cant i do at work", "label": "GENERAL"},
    {"text": "what is expected of me", "label": "GENERAL"},
    {"text": "what are my responsibilities", "label": "GENERAL"},
    {"text": "what is my job description", "label": "GENERAL"},
    {"text": "what will i be working on", "label": "GENERAL"},
    {"text": "what projects will i work on", "label": "GENERAL"},
    {"text": "what are my deliverables", "label": "GENERAL"},
    {"text": "how will success be measured", "label": "GENERAL"},
    {"text": "what are the success metrics", "label": "GENERAL"},
    {"text": "how do i know if im doing well", "label": "GENERAL"},
    {"text": "what feedback will i get", "label": "GENERAL"},
    {"text": "how often do i get feedback", "label": "GENERAL"},
    {"text": "is feedback continuous", "label": "GENERAL"},
    {"text": "what is the feedback culture", "label": "GENERAL"},
    {"text": "can i give feedback to my manager", "label": "GENERAL"},
    {"text": "is there 360 feedback", "label": "GENERAL"},
    {"text": "how does peer feedback work", "label": "GENERAL"},
    {"text": "what are working hours", "label": "GENERAL"},
    {"text": "what time should i arrive", "label": "GENERAL"},
    {"text": "what time can i leave", "label": "GENERAL"},
    {"text": "how many hours should i work", "label": "GENERAL"},
    {"text": "is overtime expected", "label": "GENERAL"},
    {"text": "do people work late", "label": "GENERAL"},
    {"text": "what is work life balance like", "label": "GENERAL"},
    {"text": "do people work weekends", "label": "GENERAL"},
    {"text": "is it ok to leave at 5", "label": "GENERAL"},
    {"text": "what is the meeting culture", "label": "GENERAL"},
    {"text": "are there a lot of meetings", "label": "GENERAL"},
    {"text": "how many meetings per week", "label": "GENERAL"},
    {"text": "what meetings will i attend", "label": "GENERAL"},
    {"text": "are meetings required", "label": "GENERAL"},
    {"text": "can i decline meetings", "label": "GENERAL"},
    {"text": "what is expected in meetings", "label":"GENERAL"},
    {"text": "should i have my camera on", "label": "GENERAL"},
    {"text": "is video required for meetings", "label": "GENERAL"},
    {"text": "what is the communication style", "label": "GENERAL"},
    {"text": "is communication formal or informal", "label": "GENERAL"},
    {"text": "how do people communicate here", "label": "GENERAL"},
    {"text": "do people use email or slack more", "label": "GENERAL"},
    {"text": "when should i email vs slack", "label": "GENERAL"},
    {"text": "what is response time expectation", "label": "GENERAL"},
    {"text": "how quickly should i respond", "label": "GENERAL"},
    {"text": "do i need to respond immediately", "label": "GENERAL"},
    {"text": "what if i cant respond right away", "label": "GENERAL"},
    {"text": "is there an after hours expectation", "label": "GENERAL"},
    {"text": "do i need to check email after hours", "label": "GENERAL"},
    {"text": "do people work after 5pm", "label": "GENERAL"},
    {"text": "what is the unwritten culture", "label": "GENERAL"},
    {"text": "what should i know thats not written", "label": "GENERAL"},
    {"text": "what are the unspoken rules", "label": "GENERAL"},
    {"text": "what do i need to know to fit in", "label": "GENERAL"},
    {"text": "how do i succeed here", "label": "GENERAL"},
    {"text": "what makes someone successful here", "label": "GENERAL"},
    {"text": "what traits are valued", "label": "GENERAL"},
    {"text": "what behaviors are rewarded", "label": "GENERAL"},
    {"text": "how do i get promoted", "label": "GENERAL"},
    {"text": "what does it take to get promoted", "label": "GENERAL"},
    {"text": "how long until promotion", "label": "GENERAL"},
    {"text": "what is the promotion timeline", "label": "GENERAL"},
    {"text": "are there growth opportunities", "label": "GENERAL"},
    {"text": "can i advance my career here", "label": "GENERAL"},
    {"text": "what career paths exist", "label": "GENERAL"},
    {"text": "where can my career go", "label": "GENERAL"},
]

df = pd.DataFrame(training_questions)
df.to_csv("./data/processed/question_training_data.csv", index=False)